#-*- coding:utf-8 -*-


# 管理员行为日志
ADMIN_ACTION_LOGIN = 0

STAGE_RANK_COPPER = 2   # 关卡铜皇冠
STAGE_RANK_SLIVER = 1   # 关卡银皇冠
STAGE_RANK_GOLD = 0     # 关卡金皇冠
STAGE_RANK_NONE = -1    # 没排行


HpIndividual = 0
AttackIndividual = 1
DefenceIndividual = 2
SpcAttackIndividual = 3
SpcDefenceIndividual = 4
SpeedIndividual = 5

# 品质 白绿蓝紫粉金
QualityWhite = 0
QualityGreen = 1
QualityBlue = 2
QualityPurple = 3
QualityPink = 4
QualityGolden = 5

# 关卡难度
STAGE_TYPE_NORMAL = 1  # 关卡普通难度
STAGE_TYPE_ELITE = 2  # 关卡精英难度
STAGE_TYPE_HERO = 3  # 关卡英雄难度
STAGE_TYPE_EXP = 4  # 经验副本
STAGE_TYPE_GOLD = 5  # 金币副本
STAGE_TYPE_MONSTER = 6  # 抓宠副本

# 怪装备
Equip_Type_1 = 1  # 徽章
Equip_Type_2 = 2  # 头环
Equip_Type_3 = 3  # 丝巾
Equip_Type_4 = 4  # 水晶
Equip_Type_5 = 5  # 羽毛
Equip_Type_Num = 5  # 总数

ITEM_TYPE_ITEM = 0  # 物品类型物品
ITEM_TYPE_EQUIP = 1  # 物品类型装备
ITEM_TYPE_FRAGMENT = 2  # 物品类型碎片
ITEM_TYPE_EQUIP_FRAGMENT = 3  # 装备碎片


# 玩家抽奖序列内容定义
#DRAW_MUST_3_STAR = 0
DRAW_MUST_PINK = 1
#DRAW_MUST_3_BIRD = 2


# 商店物品状态
SHOP_ITEM_STATE_NORMAL = 0
SHOP_ITEM_STATE_SELLOUT = 1

# 百变怪物品状态
DITTO_ITEM_STATE_NORMAL = 0
DITTO_ITEM_STATE_BUY = 1

# 玩家默认头像id
PLAYER_ROLE_ID = 10001

# 问答开始 结束时间
QUIZ_OPEN_HOUR = 19
QUIZ_END_HOUR = 21





# 游戏内事件定义
ACTION_PLAYER_LOGIN = 1
ACTION_CREATE_PLAYER = 2
ACTION_CREATE_MONSTER = 3
ACTION_SET_MONSTER_TEAM = 4
ACTION_BUY_STORAGE_NUM = 5
ACTION_BUY_STAMINA = 6
ACTION_BUY_GOLD = 7
ACTION_MODIFY_NAME = 8
ACTION_GET_VIP_GIFT = 9
ACTION_FINISH_STORY = 10
ACTION_FINISH_NEWBIE = 11
ACTION_TONIC = 12
ACTION_RECHARGE_RMB = 13
ACTION_PIKACHU_MASSAGE = 14
ACTION_PIKACHU_MASSAGE_REWARD = 15
ACTION_REWARD_MONSTER_LEVEL = 16
ACTION_REWARD_MONSTER_STAR_LEVEL = 17
ACTION_REWARD_MONSTER_KIND = 18
ACTION_REWARD_MONSTER_QUALITY = 19
ACTION_MIAO_BANK_BUY = 20
ACTION_MIAO_BANK_REWARD = 21
ACTION_MAIL_GET_ITEM = 22
ACTION_REWARD_MONTH_CARD = 23
ACTION_SIGN_IN = 24
ACTION_REWARD_STAGE_NORMAL = 25
ACTION_REWARD_STAGE_ELITE = 26
ACTION_REWARD_STAGE_HERO = 27
ACTION_REWARD_TEAM_POWER = 28
ACTION_REWARD_PLAYER_LEVEL = 29
ACTION_ITEM_SELL = 30
ACTION_ITEM_COMPOUND = 31
ACTION_FISHING = 32
ACTION_FINGER_GUESS = 33
ACTION_MONSTER_EQUIP = 34
ACTION_DRAW = 35
ACTION_TEN_DRAW = 36
ACTION_BATTLE = 37
EVOLUTION_MONSTER = 38
UPGRADE_MONSTER_SKILL = 39
UPGRADE_MONSTER_STAR_LEVEL = 40
ADVANCE_MONSTER = 41
LEVEL_UP_MONSTER = 42
RESET_MONSTER_INDIVIDUAL = 43
FREE_MONSTER = 44
ACTION_SERIES_LOGIN = 45
ACTION_DAILY_LOGIN = 46
ACTION_STONE_SHOP = 47
ACTION_ARENA_DAILY_REWARD = 48
ACTION_DAILY_RECHARGE_REWARD = 49
ACTION_SUM_RECHARGE_REWARD = 50
ACTION_STONE_SHOP_REFRESH = 51
ACTION_SET_INVITE_PLAYER = 52
ACTION_INVITE_PLAYER_REWARD = 53
ACTION_WORLD_BOSS = 54
ACTION_REWARD_CHANGE_NAME_FIRST = 55
ACTION_DITTO_REFRESH = 56
ACTION_WORLD_BOSS_INSPIRE = 57
ACTION_WORLD_BOSS_RESET = 58
ACTION_GUIDE_GAIN = 59
ACTION_MONSTER_RESET_INDIVIDUAL = 60
ACTION_RESET_INDIVIDUAL = 61

GM_CHANGE_STONE = 999

ACTION_ID_NAME_DICT = {
    1: '玩家登录',
    2: '创建玩家角色',
    3: '创建玩家首怪',
    4: '设置队伍',
    5: '购买背包',
    6: '购买体力',
    7: '购买金币',
    8: '修改名字',
    9: 'VIP礼包',
    10: '完成故事',
    11: '完成新手',
    12: '进补',
    13: '充值',
    14: '皮卡丘按摩',
    15: '获取按摩奖励',
    16: '奖励：怪等级',
    17: '奖励：怪星级',
    18: '奖励：怪种类',
    19: '奖励：怪品质',
    20: '购买喵银行',
    21: '奖励：喵银行',
    22: '邮件获取物品',
    23: '领取月卡',
    24: '签到',
    25: '奖励：普通关卡',
    26: '奖励：精英关卡',
    27: '奖励：英雄关卡',
    28: '奖励：队伍战斗力',
    29: '奖励：玩家等级',
    30: '物品出售',
    31: '合成',
    32: '钓鱼',
    33: '猜拳',
    34: '装备',
    35: '单抽奖',
    36: '十连抽奖',
    37: '战斗',
    38: '进化怪',
    39: '升级怪技能',
    40: '升级怪星级',
    41: '怪等级上限突破',
    42: '怪提升当前等级',
    43: '怪洗练',
    44: '怪放生',
    45: '连续签到',
    46: '每日签到',
    47: '钻石商城',
    48: '竞技场每日奖励',
    49: '每日充值奖励',
    50: '累计充值奖励',
    51: '钻石商场刷新',
    ACTION_SET_INVITE_PLAYER: '设置邀请的玩家',
    ACTION_INVITE_PLAYER_REWARD: '邀请玩家获得奖励',
    ACTION_WORLD_BOSS: '世界BOSS',
    ACTION_REWARD_CHANGE_NAME_FIRST: '首次改名奖励',
    ACTION_DITTO_REFRESH: '宠物商店刷新',
    ACTION_WORLD_BOSS_INSPIRE: '世界boss鼓舞',
    ACTION_WORLD_BOSS_RESET: '世界boss重置',
    ACTION_GUIDE_GAIN: '引导获取钻石',
    ACTION_MONSTER_RESET_INDIVIDUAL: '钻石洗练',
    ACTION_RESET_INDIVIDUAL: '重置洗练次数消耗钻石',
    999: '后台修改',
}


# 随机数
RANDOM_STAGE_DROP_ITEM = 1

# 聊天信息上限50条
CHAT_INFO_MAX = 50


# 游戏信息
OTHER_PHONE_LOGIN = 1  # 多设备登录

#服务器状态
SERVER_STATE_MAINTENANCE = 0
SERVER_STATE_SUGGEST = 1
SERVER_STATE_HOT = 2
SERVER_STATE_FULL = 3

SERVER_STATE_NAME_DICT = {
    SERVER_STATE_MAINTENANCE: u'维护中',
    SERVER_STATE_SUGGEST: u'推荐',
    SERVER_STATE_HOT: u'火爆',
    SERVER_STATE_FULL: u'爆满',
}

USER_STATE_NORMAL = -1  # 玩家正常状态
USER_STATE_FREEZE = 1  # 玩家冻结状态
USER_STATE_COMPANY = 2  # 玩家公司内部状态

USER_STATE_NAME_DICT = {
    USER_STATE_NORMAL: u'正常状态',
    USER_STATE_FREEZE: u'冻结状态',
    USER_STATE_COMPANY: u'公司内部状态',
}

#  游戏模块存储模块名称
MODEL_PLAYER_NAME = 'zgame_name'
MODEL_SYSTEM_MAIL_BOX = 'game_system_mail_box'
MODEL_NOTICE = 'game_notice'
MODEL_GAME_CONFIG = 'game_config'
MODEL_PLAYER_COMMIT_BUGS = 'player_commit_bugs'
MODEL_ARENA = 'game_arena'
MODEL_SERVER_QUIZ = 'server_quiz'
MODEL_WORLD_BOSS_KYUREM = 'server_world_boss_kyurem'
MODEL_WORLD_BOSS_SNORLAX = 'server_world_boss_snorlax'
MODEL_SERVER_CHAT = 'server_chat'
MODEL_SERVER_TREASURE = 'server_treasure'
MODEL_SERVER_GYM = 'server_gym'
MODEL_SERVER_EVENT_LOG = 'server_event_log'

#世界BOSS id
WORLD_BOSS_ID_SNORLAX = 1  # 卡比兽
WORLD_BOSS_ID_KYUREM = 2  # 酋雷姆
WORLD_BOSS_NUM = 3  # BOSS 数量

WORLD_BOSS_INFO_MIN = 1001  # 世界BOSS难度最小
WORLD_BOSS_INFO_MAX = 1028  # 世界BOSS难度最大

WORLD_BOSS_INFO_BASE = 1000  # 世界BOSS难度基础值
WORLD_BOSS_INDIVIDUAL = 255  # 世界BOSS个体值255

# 玩家奖励提示信息
NEW_LABEL_RECHARGE_DAILY_REWARD = 0
NEW_LABEL_RECHARGE_SUM_REWARD = 1
NEW_LABEL_USER_INVITATION = 2
NEW_LABEL_MAIL = 3
NEW_LABEL_SEVEN_LEVEL = 4
NEW_LABEL_SEVEN_POWER = 5
NEW_LABEL_DAILY_TASK = 6
NEW_LABEL_DAILY_TASK_SCORE = 7
NEW_LABEL_MAX = 8

# 玩家邀请可以领取奖励的最大次数
PLAYER_INVITATION_MAX_REWARD_NUM = 16
# 猜拳刷新时间
FINGER_REFRESH_TIME = 6 * 3600  # 猜拳刷新时间秒 6 * 3600
# FINGER_REFRESH_TIME = 1 * 60   # 猜拳刷新时间秒 6 * 3600
FISHING_REFRESH_TIME = 300  # 钓鱼刷新时间 60*5


# 金刚玉魂 宝物升阶
ITEM_TREASURE_PHASE_UP = 80306

# 太阳石itemID
SUN_STONE_ID = 80008

# 月亮石itemID
ITEM_MOON_STONE = 80009

# 银色材料itemID
ITEM_METAL_SILVERY = 80301
# 金色材料itemID
ITEM_METAL_GOLD = 80302
# 百变怪道具
ITEM_DITTO_TID = 80049
# 装备强化材料ID
ITEM_EQUIP_LEVEL_UP = 80303
# 小药瓶
ITEM_SMALL_EXP_TID = 80101
# 中药瓶
ITEM_MID_EXP_TID = 80102
# 大药瓶
ITEM_BIG_EXP_TID = 80103

# 普通关扫荡材料
ITEM_STAGE_NORMAL_TID = 80047
# 英雄经英关扫荡材料
ITEM_STAGE__HERO_TID = 80048


# 喇叭
ITEM_CHAT_TID = 80304
# 喇叭消耗钻石
ITEM_CHAT_STONE = 10
# 聊天最小时间间隔
CHAT_TIME_LIMIT = 10
# 最大聊天长度
CHAT_CONTENT_LIMIT = 255


# 世界boss攻击排名999
WORLD_BOSS_RANK_NUM = 999
WORLD_BOSS_SHOP_POINT_MAX = 999999

# 竞技场初始排名1000
ARENA_INIT_RANK = 1000
#竞技场纹章数上限
ARENA_EMBLEM_MAX = 999999


# 抽奖模块
ONE_DRAW_COST_STONE = 300
TEN_DRAW_COST_STONE = 2880
DRAW_TYPE_ONE = 1
DRAW_TYPE_TEN = 2
DRAW_CONTENT_TYPE_MONSTER = 1
DRAW_CONTENT_TYPE_EQUIP = 3
DRAW_CONTENT_TYPE_ITEM = 2
DRAW_CONTENT_TYPE_FRAGMENT = 4

# 后台活动安排部分
ACTIVITY_DAILY_RECHARGE = 0  # 活动单日充值活动（客户端活动页签）
ACTIVITY_SUM_RECHARGE = 1  # 活动累计充值活动（客户端活动页签）
ACTIVITY_DOUBLE_RECHARGE = 2  # 充值双倍（客户端商城）
ACTIVITY_STONE_SHOP_DISCOUNT = 3 #钻石商城折扣
ACTIVITY_DRAW_DISCOUNT = 4 #抽卡折扣
ACTIVITY_REWARD_TIMES_NORMAL_STAGE = 5 #普通副本
ACTIVITY_REWARD_TIMES_HARD_STAGE = 6 #困难副本
ACTIVITY_REWARD_TIMES_ARENA = 7 #竞技场
ACTIVITY_REWARD_TIMES_GYM = 8 #道馆
ACTIVITY_REWARD_TIMES_TREASURE = 9 #夺宝
ACTIVITY_REWARD_TIMES_FISHING = 10 #钓鱼
ACTIVITY_REWARD_TIMES_FINGER_GUESS = 11 #猜拳
ACTIVITY_REWARD_TIME_LIMITED_RECHARGE_SHORT = 12 #短期限时充值
ACTIVITY_REWARD_TIME_LIMITED_RECHARGE_LONG = 13 #长期限时充值
ACTIVITY_REWARD_ONE_RECHARGE = 14 #单笔金额奖励
ACTIVITY_SEVEN_LEVEL_REWARD = 15 #7天等级奖励
ACTIVITY_SEVEN_POWER_REWARD = 16 #7天战力奖励

ACTIVITY_FORENOTICE1 = 17 #活动预告1
ACTIVITY_FORENOTICE2 = 18 #活动预告2
ACTIVITY_REWARD_STONE_CONSUMPTION = 19 #钻石消耗
ACTIVITY_HOLIDAY_SHOP = 20 #假日商店
ACTIVITY_TIME_LIMITED_SHOP = 21 #便利商店
ACTIVITY_TIME_LIMITED_SHIFT_SHOP = 22 #友好商店
ACTIVITY_REWARD23 = 23 #钓鱼
ACTIVITY_REWARD24 = 24 #钓鱼
ACTIVITY_REWARD25 = 25 #钓鱼
ACTIVITY_REWARD26 = 26 #钓鱼
ACTIVITY_REWARD27 = 27 #钓鱼
ACTIVITY_REWARD28 = 28 #钓鱼
ACTIVITY_REWARD29 = 29 #钓鱼
# 运营活动的执行的最大次数  普通副本 困难副本 竞技场 道馆 夺宝 钓鱼 猜拳
ACTIVITY_REWARD_MAX_TIMES = 999
# 运营活动的执行的钻石消耗最大值
ACTIVITY_REWARD_STONE_CONSUMPTION_MAX = 99999999

ACTIVITY_MAX = 23

ACTIVITY_NAME_DICT = {
    ACTIVITY_DAILY_RECHARGE: u'当日返利',
    ACTIVITY_SUM_RECHARGE: u'满额返利',
    ACTIVITY_DOUBLE_RECHARGE: u'充值双倍',
    ACTIVITY_STONE_SHOP_DISCOUNT: u'钻石商城折扣',
    ACTIVITY_DRAW_DISCOUNT: u'抽卡折扣',
    ACTIVITY_REWARD_TIMES_NORMAL_STAGE: u'普通副本',
    ACTIVITY_REWARD_TIMES_HARD_STAGE: u'困难副本',
    ACTIVITY_REWARD_TIMES_ARENA: u'竞技场',
    ACTIVITY_REWARD_TIMES_GYM: u'道馆',
    ACTIVITY_REWARD_TIMES_TREASURE: u'夺宝',
    ACTIVITY_REWARD_TIMES_FISHING: u'钓鱼',
    ACTIVITY_REWARD_TIMES_FINGER_GUESS: u'猜拳',
    ACTIVITY_REWARD_TIME_LIMITED_RECHARGE_SHORT: u'限时充值-短期',
    ACTIVITY_REWARD_TIME_LIMITED_RECHARGE_LONG: u'限时充值-长期',
    ACTIVITY_REWARD_ONE_RECHARGE: u'单笔金额奖励',
    ACTIVITY_SEVEN_LEVEL_REWARD: u'开服7天等级奖励',
    ACTIVITY_SEVEN_POWER_REWARD: u'开服7天战力奖励',
    ACTIVITY_FORENOTICE1: u'活动预告',
    ACTIVITY_FORENOTICE2: u'活动预告2',
    ACTIVITY_REWARD_STONE_CONSUMPTION: u'钻石消耗',
    ACTIVITY_HOLIDAY_SHOP: u'假日商店',
    ACTIVITY_TIME_LIMITED_SHOP: u'便利商店',
    ACTIVITY_TIME_LIMITED_SHIFT_SHOP: u'友好商店',
    ACTIVITY_REWARD23: u'活动奖励23',
    ACTIVITY_REWARD24: u'活动奖励24',
    ACTIVITY_REWARD25: u'活动奖励25',
    ACTIVITY_REWARD26: u'活动奖励26',
    ACTIVITY_REWARD27: u'活动奖励27',
    ACTIVITY_REWARD28: u'活动奖励28',
    ACTIVITY_REWARD29: u'活动奖励29',

}
#运营活动状态
ACTIVITY_STATE_NORMAL = 0
ACTIVITY_STATE_ON = 1
ACTIVITY_STATE_OFF = 2

ACTIVITY_STATE_NAME_DICT = {
    ACTIVITY_STATE_NORMAL: u'正常状态',
    ACTIVITY_STATE_ON: u'强制开启',
    ACTIVITY_STATE_OFF: u'强制关闭',
}

# 世界boss统计
WORLD_BOSS_ACTION_ATTACK = 0
WORLD_BOSS_ACTION_CREATE = 1
WORLD_BOSS_ACTION_REWARD = 2
WORLD_BOSS_ACTION_INSPIRE = 3
WORLD_BOSS_ACTION_RESET = 4

WORLD_BOSS_ACTION_DICT = {
    WORLD_BOSS_ACTION_ATTACK: '攻击boss',
    WORLD_BOSS_ACTION_CREATE: '创建boss',
    WORLD_BOSS_ACTION_REWARD: '奖励物品',
    WORLD_BOSS_ACTION_INSPIRE: 'boss鼓舞',
    WORLD_BOSS_ACTION_RESET: 'boss重置',
}

# 装备兑换，强化统计
EQUIP_ACTION_EXCHANGE = 0
EQUIP_ACTION_LEVEL_UP = 1

EQUIP_ACTION_DICT = {
    EQUIP_ACTION_EXCHANGE: '装备兑换',
    EQUIP_ACTION_LEVEL_UP: '装备强化',
}

# 碎片合成统计
COMPOUND_ACTION_EQUIP = 0
COMPOUND_ACTION_MONSTER = 1

COMPOUND_ACTION_DICT = {
    COMPOUND_ACTION_EQUIP: '碎片合成装备',
    COMPOUND_ACTION_MONSTER: '碎片合成怪',
}

# 玩家邀请统计
INVITION_ACTION_USER = 0
INVITION_ACTION_REWARD = 1

INVITION_ACTION_DICT = {
    INVITION_ACTION_USER: '邀请玩家',
    INVITION_ACTION_REWARD: '获取邀请奖励',
}

# 夺宝
MAX_PLAYER_TREASURE_COUNT = 10  # 玩家最大夺宝次数


# 玩家邀请统计
INVITION_ACTION_USER = 0

# 兑换码长度 8位
EXCHANGE_CODE_LEN = 10

# 玩家兑换码平台标识
PLAT_FORM_HAIMA_ONLINE = 800003 #线上ios海马
# PLAT_FORM_INNER = 0
PLAT_FORM_INNER = 999999
PLAT_FORM_COMMON = -1
# RECHARGE_PLATFORM_TYPE_ANYSDK = 2 #anysdk
RECHARGE_PLATFORM_TYPE_FEILIU = 800004  # 飞流
RECHARGE_PLATFORM_IOS_91 = 500001  # iOS-91手机助手
RECHARGE_PLATFORM_IOS_ITOOLS = 500004  # iOS-iTools
RECHARGE_PLATFORM_IOS_KUAIYONG = 500015  # iOS-快用
RECHARGE_PLATFORM_IOS_HAIMA = 500017  # iOS-海马助手
RECHARGE_PLATFORM_IOS_AI_SI = 500020  # iOS-爱思助手
RECHARGE_PLATFORM_IOS_XY = 500030  # iOS-XY助手
RECHARGE_PLATFORM_IOS_TONGBUTUI = 500002  # 同步推
RECHARGE_PLATFORM_IOS_PP = 500003  # pp助手
RECHARGE_PLATFORM_IOS_XX = 500035  # 叉叉助手
RECHARGE_PLAT_FORM_IAPPLE = 800006 #爱苹果
RECHARGE_PLATFORM_ANDROID_UC = 255  # Android-UC
RECHARGE_PLATFORM_ANDROID_FEILIU = 85  # Android-飞流
RECHARGE_PLATFORM_ANDROID_APPLE_SHOP = 500026  # Android-苹果商城
RECHARGE_PLATFORM_ANDROID_ZHUOYI = 890  # Android-卓易
RECHARGE_PLATFORM_ANDROID_OPPO_GAME_CENTER = 20  # Android-OPPO可可游戏中心0
RECHARGE_PLATFORM_ANDROID_BAIDU91 = 7  # Android-百度91
RECHARGE_PLATFORM_ANDROID_360_HELPER = 23  # Android-360手机助手0
RECHARGE_PLATFORM_ANDROID_XIAOMI = 66  # Android-小米应用
RECHARGE_PLATFORM_ANDROID_TENGXUN_APP = 550  # Android-腾讯应用宝0
RECHARGE_PLATFORM_ANDROID_BAIDU_GAME = 110000  # Android-百度游戏0
RECHARGE_PLATFORM_ANDROID_WANDOUJIA = 116  # Android-豌豆荚
RECHARGE_PLATFORM_ANDROID_ANZHI_MARKET = 5  # Android-安智市场
RECHARGE_PLATFORM_ANDROID_PPS = 442  # Android-PPS
RECHARGE_PLATFORM_ANDROID_APP_GATHER = 9  # Android-应用汇0
RECHARGE_PLATFORM_ANDROID_YOUKU = 466  # Android-优酷
RECHARGE_PLATFORM_ANDROID_SOUGOU_GAME_CENTER = 800  # Android-搜狗游戏中心
RECHARGE_PLATFORM_ANDROID_LENOVO_APP = 16  # Android-联想应用0
RECHARGE_PLATFORM_ANDROID_THUMB_PLAY = 247  # Android-拇指玩0
RECHARGE_PLATFORM_ANDROID_SHANGHAI_YIWAN = 914  # Android-上海益玩
RECHARGE_PLATFORM_ANDROID_4399 = 108  # Android-4399开放平台
RECHARGE_PLATFORM_ANDROID_KUPAI = 78  # Android-酷派
RECHARGE_PLATFORM_ANDROID_DANGLE = 3  # Android-当乐0
RECHARGE_PLATFORM_ANDROID_BBK_VIVO = 368  # Android-步步高VIVO
RECHARGE_PLATFORM_ANDROID_HUAWEI = 54  # Android-华为0
RECHARGE_PLATFORM_ANDROID_JINLI_GAME = 286  # Android-金立游戏
RECHARGE_PLATFORM_ANDROID_JIFENG = 2  # Android-机锋0
RECHARGE_PLATFORM_ANDROID_HAIMA = 1104  # Android-海马安卓0
RECHARGE_PLATFORM_ANDROID_MEIZU_APP = 14  # Android-魅族应用0
RECHARGE_PLATFORM_ANDROID_JULE = 551  # Android-聚乐
RECHARGE_PLATFORM_ANDROID_ZHANGYUE = 800007  # Android-掌阅
RECHARGE_PLATFORM_ANDROID_37_GAME = 931  # Android-37游戏0
RECHARGE_PLATFORM_ANDROID_XX = 1201  # Android-叉叉助手0


# 玩家兑换码平台名标识
PLAT_FORM_NAME_DICT = {
    PLAT_FORM_COMMON: u'通平台',
    PLAT_FORM_HAIMA_ONLINE: u'海马',
    PLAT_FORM_INNER: u'测试服',
    RECHARGE_PLATFORM_TYPE_FEILIU: u'飞流',
    # RECHARGE_PLATFORM_TYPE_ANYSDK: u'anysdk',
    RECHARGE_PLATFORM_IOS_91: u'iOS-91手机助手',
    RECHARGE_PLATFORM_IOS_ITOOLS: u'iOS-iTools',
    RECHARGE_PLATFORM_IOS_KUAIYONG: u'iOS-快用',
    RECHARGE_PLATFORM_IOS_HAIMA: u'iOS-海马助手',
    RECHARGE_PLATFORM_IOS_AI_SI: u'iOS-爱思助手',
    RECHARGE_PLATFORM_IOS_XY: u'iOS-XY助手',
    RECHARGE_PLATFORM_IOS_TONGBUTUI: u'同步推',
    RECHARGE_PLATFORM_IOS_PP: u'pp助手',
    RECHARGE_PLATFORM_IOS_XX: u'叉叉助手',
    RECHARGE_PLAT_FORM_IAPPLE: u'爱苹果',
    RECHARGE_PLATFORM_ANDROID_UC: u'UC',
    RECHARGE_PLATFORM_ANDROID_FEILIU: u'Android-飞流',
    RECHARGE_PLATFORM_ANDROID_APPLE_SHOP: u'Android-苹果商城',
    RECHARGE_PLATFORM_ANDROID_ZHUOYI: u'Android-卓易',
    RECHARGE_PLATFORM_ANDROID_OPPO_GAME_CENTER: u'Android-OPPO可可游戏中心',
    RECHARGE_PLATFORM_ANDROID_BAIDU91: u'Android-百度91',
    RECHARGE_PLATFORM_ANDROID_360_HELPER: u'Android-360手机助手',
    RECHARGE_PLATFORM_ANDROID_XIAOMI: u'Android-小米应用',
    RECHARGE_PLATFORM_ANDROID_TENGXUN_APP: u'Android-腾讯应用宝',
    RECHARGE_PLATFORM_ANDROID_BAIDU_GAME: u'Android-百度游戏',
    RECHARGE_PLATFORM_ANDROID_WANDOUJIA: u'Android-豌豆荚',
    RECHARGE_PLATFORM_ANDROID_ANZHI_MARKET: u'Android-安智市场',
    RECHARGE_PLATFORM_ANDROID_PPS: u'Android-PPS',
    RECHARGE_PLATFORM_ANDROID_APP_GATHER: u'Android-应用汇',
    RECHARGE_PLATFORM_ANDROID_YOUKU: u'Android-优酷',
    RECHARGE_PLATFORM_ANDROID_SOUGOU_GAME_CENTER: u'Android-搜狗游戏中心',
    RECHARGE_PLATFORM_ANDROID_LENOVO_APP: u'Android-联想应用',
    RECHARGE_PLATFORM_ANDROID_THUMB_PLAY: u'Android-拇指玩',
    RECHARGE_PLATFORM_ANDROID_SHANGHAI_YIWAN: u'Android-上海益玩',
    RECHARGE_PLATFORM_ANDROID_4399: u'Android-4399开放平台',
    RECHARGE_PLATFORM_ANDROID_KUPAI: u'Android-酷派',
    RECHARGE_PLATFORM_ANDROID_DANGLE: u'Android-当乐',
    RECHARGE_PLATFORM_ANDROID_BBK_VIVO: u'Android-步步高VIVO',
    RECHARGE_PLATFORM_ANDROID_HUAWEI: u'Android-华为',
    RECHARGE_PLATFORM_ANDROID_JINLI_GAME: u'Android-金立游戏',
    RECHARGE_PLATFORM_ANDROID_JIFENG: u'Android-机锋',
    RECHARGE_PLATFORM_ANDROID_HAIMA: u'Android-海马安卓',
    RECHARGE_PLATFORM_ANDROID_MEIZU_APP: u'Android-魅族应用',
    RECHARGE_PLATFORM_ANDROID_JULE: u'Android-聚乐',
    RECHARGE_PLATFORM_ANDROID_ZHANGYUE: u'Android-掌阅',
    RECHARGE_PLATFORM_ANDROID_37_GAME: u'Android-37游戏',
    RECHARGE_PLATFORM_ANDROID_XX: u'Android-叉叉助手',

}

# 玩家兑换码平台名
PLAT_FORM_CSV_NAME_DICT = {
    PLAT_FORM_COMMON: '通平台',
    PLAT_FORM_HAIMA_ONLINE: '海马',
    PLAT_FORM_INNER: '测试服',
    RECHARGE_PLATFORM_TYPE_FEILIU: '飞流',
    # RECHARGE_PLATFORM_TYPE_ANYSDK: 'anysdk',
    RECHARGE_PLATFORM_IOS_91: 'iOS-91手机助手',
    RECHARGE_PLATFORM_IOS_ITOOLS: 'iOS-iTools',
    RECHARGE_PLATFORM_IOS_KUAIYONG: 'iOS-快用',
    RECHARGE_PLATFORM_IOS_HAIMA: 'iOS-海马助手',
    RECHARGE_PLATFORM_IOS_AI_SI: 'iOS-爱思助手',
    RECHARGE_PLATFORM_IOS_XY: 'iOS-XY助手',
    RECHARGE_PLATFORM_IOS_TONGBUTUI: '同步推',
    RECHARGE_PLATFORM_IOS_PP: 'pp助手',
    RECHARGE_PLATFORM_IOS_XX: '叉叉助手',
    RECHARGE_PLAT_FORM_IAPPLE: '爱苹果',
    RECHARGE_PLATFORM_ANDROID_UC: 'UC',
    RECHARGE_PLATFORM_ANDROID_FEILIU: 'Android-飞流',
    RECHARGE_PLATFORM_ANDROID_APPLE_SHOP: 'Android-苹果商城',
    RECHARGE_PLATFORM_ANDROID_ZHUOYI: 'Android-卓易',
    RECHARGE_PLATFORM_ANDROID_OPPO_GAME_CENTER: 'Android-OPPO可可游戏中心',
    RECHARGE_PLATFORM_ANDROID_BAIDU91: 'Android-百度91',
    RECHARGE_PLATFORM_ANDROID_360_HELPER: 'Android-360手机助手',
    RECHARGE_PLATFORM_ANDROID_XIAOMI: 'Android-小米应用',
    RECHARGE_PLATFORM_ANDROID_TENGXUN_APP: 'Android-腾讯应用宝',
    RECHARGE_PLATFORM_ANDROID_BAIDU_GAME: 'Android-百度游戏',
    RECHARGE_PLATFORM_ANDROID_WANDOUJIA: 'Android-豌豆荚',
    RECHARGE_PLATFORM_ANDROID_ANZHI_MARKET: 'Android-安智市场',
    RECHARGE_PLATFORM_ANDROID_PPS: 'Android-PPS',
    RECHARGE_PLATFORM_ANDROID_APP_GATHER: 'Android-应用汇',
    RECHARGE_PLATFORM_ANDROID_YOUKU: 'Android-优酷',
    RECHARGE_PLATFORM_ANDROID_SOUGOU_GAME_CENTER: 'Android-搜狗游戏中心',
    RECHARGE_PLATFORM_ANDROID_LENOVO_APP: 'Android-联想应用',
    RECHARGE_PLATFORM_ANDROID_THUMB_PLAY: 'Android-拇指玩',
    RECHARGE_PLATFORM_ANDROID_SHANGHAI_YIWAN: 'Android-上海益玩',
    RECHARGE_PLATFORM_ANDROID_4399: 'Android-4399开放平台',
    RECHARGE_PLATFORM_ANDROID_KUPAI: 'Android-酷派',
    RECHARGE_PLATFORM_ANDROID_DANGLE: 'Android-当乐',
    RECHARGE_PLATFORM_ANDROID_BBK_VIVO: 'Android-步步高VIVO',
    RECHARGE_PLATFORM_ANDROID_HUAWEI: 'Android-华为',
    RECHARGE_PLATFORM_ANDROID_JINLI_GAME: 'Android-金立游戏',
    RECHARGE_PLATFORM_ANDROID_JIFENG: 'Android-机锋',
    RECHARGE_PLATFORM_ANDROID_HAIMA: 'Android-海马安卓',
    RECHARGE_PLATFORM_ANDROID_MEIZU_APP: 'Android-魅族应用',
    RECHARGE_PLATFORM_ANDROID_JULE: 'Android-聚乐',
    RECHARGE_PLATFORM_ANDROID_ZHANGYUE: 'Android-掌阅',
    RECHARGE_PLATFORM_ANDROID_37_GAME: 'Android-37游戏',
    RECHARGE_PLATFORM_ANDROID_XX: 'Android-叉叉助手',

}

# 每日任务
DAILY_TASK_REWATD_NUM = 5  # 领奖包数量
# 挑战竞技场
DAILY_TASK_ARENA = 1
# 购买体力
DAILY_TASK_BUY_STAMINA = 2
# 购买金币
DAILY_TASK_BUY_GOLD = 3
# 钻石/免费抽奖
DAILY_TASK_DRAW = 4
# 宠物升星
DAILY_TASK_UPGRADE_STAR_MONSTER = 5
# 宠物洗练
DAILY_TASK_RESET_INDIVIDUAL_MONSTER = 6
# 宠物技能强化
DAILY_TASK_UPGRADE_MONSTER_Skill = 7
# 装备强化
DAILY_TASK_LEVEL_UP_EQUIP = 8
# 猜拳
DAILY_TASK_FINGER_GUESS_WIN = 9
# 钓鱼
DAILY_TASK_FISHING = 10
# 普通副本胜利/扫荡
DAILY_TASK_NORMAL_STAGE = 11
# 精英副本胜利
# DAILY_TASK_ELIFE_STAGE= 12
# 问答
DAILY_TASK_QA = 12
# 皮卡丘按摩
DAILY_TASK_MASSAGE = 13
# 进补领体力
DAILY_TASK_TONIC = 14
# 宠物使用营养液升级
DAILY_TASK_LEVEL_UP_MONSTER = 15
# 宠物使用太阳石进化
DAILY_TASK_Evolution_Monster = 16
# 英雄副本胜利/扫荡
DAILY_TASK_HERO_STAGE = 17
# 抓宠副本胜利
DAILY_TASK_CATCH_MONSTER_STAGE = 18
# 经验/金币副本胜利
DAILY_TASK_EXP_GOLD_STAGE = 19
#世界Boss战斗
DAILY_TASK_WORLD_BOSS = 20
# 道馆挑战
DAILY_TASK_GYM_CHALLENGE = 21
# 夺宝
DAILY_TASK_TREASURE = 22

#宠物最高进化阶
MONSTER_EVOLUTION_MAX = 10

# 商城
ACTION_SHOP_STONE = 0
ACTION_SHOP_PVP = 1
ACTION_SHOP_STAGE = 2
ACTION_SHOP_WORLD = 3

ACTION_SHOP_DICT = {
    ACTION_SHOP_STONE: '钻石商城',
    ACTION_SHOP_PVP: 'PVP 商城',
    ACTION_SHOP_STAGE: '购买关卡次数商城',
    ACTION_SHOP_WORLD: '世界boss商城',
}

# 7天登陆
LOGIN_REWARD_DAYS_NUM = 8  # 登陆奖励最大天数
# 皮卡丘
MONSTER_TID_PIKAQIU = 25  # 皮卡丘tid
# 小火龙
MONSTER_TID_CHARMANDER = 4  # 小火龙tid charmeleon
# 卡比兽
MONSTER_TID_BANJILA = 143  # 卡比兽tid

# 抓宠定义
# CATCH_MONSTER_MAX_RESET = 19

# 答题
QUIZ_REWARD_GOLD = 10000 #答对每题的奖励数
QUIZ_REWARD_GOLD_EXTRA = 5000 #题目全部打完的格外奖励

# 战斗力可调比率
COMBAT_POWER_RANGE = 0.5

# 事件日志统计
EVENT_ACTION_CREATE_ROLE = 0
EVENT_ACTION_ROLE_LOGIN = 1     #角色登陆
EVENT_ACTION_LOGOUT = 2
EVENT_ACTION_DISCONNECTED = 3
EVENT_ACTION_MUTE = 4
EVENT_ACTION_GET_QUEST = 5
EVENT_ACTION_FINISH_QUEST = 6
EVENT_ACTION_ARENA_WIN = 7
EVENT_ACTION_ARENA_FAIL = 8
EVENT_ACTION_STONE_SHOP_BUY = 9     #宝石商店购买
EVENT_ACTION_DITTO_SHOP_BUY = 10
EVENT_ACTION_PVP_SHOP_BUY = 11
EVENT_ACTION_WORLD_BOSS_SHOP_BUY = 12
EVENT_ACTION_ROLE_LEVEL_UP = 13
EVENT_ACTION_STAGE_NORMAL_WIN = 14     # 普通副本战斗胜利
EVENT_ACTION_STAGE_HERO_WIN = 15   # 困难副本战斗胜利
EVENT_ACTION_STAGE_EXP_WIN = 16    # 经验副本战斗胜利
EVENT_ACTION_STAGE_GOLD_WIN = 17   # 金币副本战斗胜利
EVENT_ACTION_STAGE_NORMAL_FAIL = 18    # 普通副本战斗失败
EVENT_ACTION_STAGE_HERO_FAIL = 19  # 困难副本战斗失败
EVENT_ACTION_STAGE_EXP_FAIL = 20   # 经验副本战斗失败
EVENT_ACTION_STAGE_GOLD_FAIL = 21  # 金币副本战斗失败
EVENT_ACTION_FISHING_ONCE = 22
EVENT_ACTION_FISHING_LOOP = 23
EVENT_ACTION_I_INVITE_REWARD = 24
EVENT_ACTION_INVITE_ME_REWARD = 25
EVENT_ACTION_EQUIP_SELL = 26  # 装备售出
EVENT_ACTION_GYM_FAIL = 27  # 挑战道馆失败
EVENT_ACTION_GYM_RESET = 28     # 道馆重置
EVENT_ACTION_MONSTER_FREE = 29  # 宠物放生

EVENT_ACTION_FINGER_GUESS_EXCHANGE = 31
EVENT_ACTION_SUN_STONE_EXCHANGE = 32
EVENT_ACTION_EXCHANGE_MONSTER = 33
EVENT_ACTION_GET_SYSTEM_MAIL_REWARD = 34
EVENT_ACTION_GET_MONSTER_LEVEL = 35
EVENT_ACTION_GET_MONSTER_STAR_LEVEL = 36
EVENT_ACTION_GET_MONSTER_KIND = 37
EVENT_ACTION_GET_MONSTER_QUALITY = 38
EVENT_ACTION_GET_CATCH_MONSTER_RESULT = 39
EVENT_ACTION_ONE_DRAW = 40
EVENT_ACTION_TEN_DRAW = 41
EVENT_ACTION_EXCHANGE_ITEM = 42
EVENT_ACTION_EXCHANGE_GIFT = 43
# EVENT_ACTION_FISHING = 44
EVENT_ACTION_GET_FIRST_RECHARGE_GIFT = 45
EVENT_ACTION_DROP_ITEM_PACKET_IN_WB = 46
EVENT_ACTION_LOGIN_7_REWARD = 47
EVENT_ACTION_MASSAGE_REWARD = 48
EVENT_ACTION_FREE_MONSTER_GET_ITEMS = 49
# EVENT_ACTION_INVITATION_REWARD = 50
EVENT_ACTION_DAILY_RECHARGE_REWARD = 51
EVENT_ACTION_FINISH_GUIDE = 52
EVENT_ACTION_SUM_RECHARGE_REWARD = 53


EVENT_ACTION_SIGN_30 = 56
# EVENT_ACTION_BUY_STONE_SHOP_ITEM = 57
EVENT_ACTION_TRIAL_BATTLE_WIN = 58
EVENT_ACTION_VIP_DAILY_REWARD = 59
EVENT_ACTION_VIP_LEVEL_GIFT = 60
EVENT_ACTION_SELL_ITEM = 61
EVENT_ACTION_DAILY_REWARD_GOLD = 62
EVENT_ACTION_STAGE_NORMAL_REWARD = 63
EVENT_ACTION_STAGE_ELITE_REWARD = 64
EVENT_ACTION_STAGE_HERO_REWARD = 65
EVENT_ACTION_TEAM_POWER_REWARD = 66
EVENT_ACTION_STAGE_NORMAL_CROWN = 67
EVENT_ACTION_STAGE_ELITE_CROWN = 68
EVENT_ACTION_STAGE_HERO_CROWN = 69
EVENT_ACTION_DAILY_TASK_SCORE_REWARD = 70
EVENT_ACTION_GYM_WIN = 71
EVENT_ACTION_ARENA_DAILY_REWARD = 72
EVENT_ACTION_QUIZ_ANSWER_TRUE = 73
EVENT_ACTION_WORLD_BOSS_REWARD = 74
EVENT_ACTION_TREASURE_COMPOSE = 75
EVENT_ACTION_LEVEL_GIFT = 76
EVENT_ACTION_MONTH_CARD = 77
EVENT_ACTION_CHANGE_NAME = 78
EVENT_ACTION_EQUIP_LEVEL_UP = 79
EVENT_ACTION_WB_GOLD_INSPIRE = 80
EVENT_ACTION_CHAT = 81
EVENT_ACTION_STONE_RESET_STONE_SHOP = 82
EVENT_ACTION_RESET_INDIVIDUAL_COUNT = 83
EVENT_ACTION_ARENA_BUY_COUNT = 84
EVENT_ACTION_WB_STONE_INSPIRE = 85
EVENT_ACTION_WB_RESET_COUNT = 86
EVENT_ACTION_BUY_STAGE_COUNT = 87
EVENT_ACTION_ADVANCE_MONSTER = 88
EVENT_ACTION_EVOLUTE_MONSTER = 89
EVENT_ACTION_LEVEL_UP_MONSTER = 90
EVENT_ACTION_UPGRADE_MONSTER_SKILL = 91
EVENT_ACTION_GYM_SHOP_BUY = 92
EVENT_ACTION_STAGE_MOP = 93
EVENT_ACTION_COMPOUND_EQUIP = 94
EVENT_ACTION_COMPOUND_MONSTER = 95
EVENT_ACTION_GYM_REWARD = 96
# EVENT_ACTION_SHOP_BUY_DITTO = 97
EVENT_ACTION_LOGIN_SERIES_REWARD = 98
EVENT_ACTION_SHOP_EXCHANGE = 99
EVENT_ACTION_SIGN_30_SERIES = 100
EVENT_ACTION_LOTTERY_REWARD = 101
EVENT_ACTION_ADVANCE_TITLE = 102
EVENT_ACTION_BUY_GOLD = 103
EVENT_ACTION_UPDATE_STAR_MONSTER = 104
EVENT_ACTION_RESET_INDIVIDUAL_MONSTER = 105
EVENT_ACTION_BUY_MIAO_BANK = 106
EVENT_ACTION_BUY_STORAGENUM = 107
EVENT_ACTION_BUY_STAMINA = 108
EVENT_ACTION_MODIFY_NAME = 109
EVENT_ACTION_STONE_RESET_INDIVIDUAL_MONSTER = 110
EVENT_ACTION_GET_MIAOBANK_REWARD = 111
EVENT_ACTION_STONE_RESET_DITTO_SHOP = 112
EVENT_ACTION_STONE_RESET_GYM_SHOP = 113
EVENT_ACTION_STONE_RESET_PVP_SHOP = 114
EVENT_ACTION_STONE_RESET_WB_SHOP = 115


EVENT_ACTION_GYM_MOP = 118
EVENT_ACTION_MONSTER_REBIRTH = 119
EVENT_ACTION_EQUIP_EXCHANGE_GET_ITEMS = 120
EVENT_ACTION_FINISH_NEWBIE = 121
EVENT_ACTION_DAILY_REWARD_STONE = 122
EVENT_ACTION_DAILY_TASK_TASK_REWARD = 123   # 每日任务部分 任务领取奖励
EVENT_ACTION_TREASURE_LEVEL_UP = 124  # 宝石强化升级
EVENT_ACTION_TREASURE_PHASE_UP = 125  # 宝石升阶
EVENT_ACTION_ACTIVITY_SEVEN_LEVEL_REWARD = 126   # 活动1__开服七天等级奖励
EVENT_ACTION_ACTIVITY_SEVEN_POWER_REWARD = 127   # 活动1__开服七天战力奖励
EVENT_ACTION_EQUIP_LEVEL_UP_MULTI = 128   # 强化装备多次
EVENT_ACTION_ACTIVITY_NORMAL_STAGE_REWARD = 129   # 活动1__普通副本
EVENT_ACTION_ACTIVITY_HARD_STAGE_REWARD = 130   # 活动1__困难副本
EVENT_ACTION_ACTIVITY_ARENA_REWARD = 131   # 活动1__竞技场
EVENT_ACTION_ACTIVITY_GYM_REWARD = 132   # 活动1__道馆
EVENT_ACTION_ACTIVITY_TREASURE_REWARD = 133   # 活动1__夺宝
EVENT_ACTION_ACTIVITY_FISHING_REWARD = 134   # 活动1__钓鱼
EVENT_ACTION_ACTIVITY_FINGER_GUESS_REWARD = 135   # 活动1__猜拳
EVENT_ACTION_ACTIVITY_RECHARGE_SHORT = 136   # 活动1__短期充值
EVENT_ACTION_ACTIVITY_RECHARGE_LONG = 137   # 活动1__长期充值
EVENT_ACTION_ZONE_GOLD_CROWN_REWARD = 138  # 获取关卡金皇冠奖励
EVENT_ACTION_ZONE_PASS_REWARD = 139  # 获取关卡通过奖励
EVENT_ACTION_GET_TONIC = 140  # 进补
EVENT_ACTION_TREASURE_BATTLE_WIN = 141  # 夺宝战斗胜利
EVENT_ACTION_TREASURE_BATTLE_FAIL = 142  # 夺宝战斗失败
EVENT_ACTION_WORLD_BOSS_ATTACK = 143  # 世界BOSS攻击
EVENT_ACTION_TRIAL_BATTLE_FAIL = 144  # 试炼战斗失败
EVENT_ACTION_TREASURE_COUNT_RESET = 145    # 夺宝次数重置
EVENT_ACTION_EXP_STAGE_BUY_COUNT = 146    # 经验副本购买挑战次数
EVENT_ACTION_GOLD_STAGE_BUY_COUNT = 147    # 金币副本购买挑战次数
EVENT_ACTION_RECHARGE_PLAYER = 148  # 外部玩家充值
EVENT_ACTION_RECHARGE_INNER = 149  # 内部充值

EVENT_ACTION_COMBAT_POWER_ERROR = 150  # 战斗力数据异常
EVENT_ACTION_ACTIVITY_ONE_RECHARGE = 151   # 活动1__单笔充值
EVENT_ACTION_ACTIVITY_WEIXIN_SHARE = 152   # 活动1__微信分享
EVENT_ACTION_ACTIVITY_REGIST_RECHARGE = 153   # 活动1__豪华充值
EVENT_ACTION_BUDDY_CONTACT = 154 #与好友通讯
EVENT_ACTION_REWARD_BUDDY_CONTACT = 155 #与好友通讯
# 联盟部分
EVENT_ACTION_STONE_RESET_UNION_SHOP = 156  # 联盟商店重置

EVENT_ACTION_ACTIVITY_STONE_CONSUMPTION_REWARD = 157   # 活动_钻石消耗奖励
EVENT_ACTION_HISTORY_BUDDY_MAX_REWARD = 158 #宝藏 历史好友最高数

EVENT_ACTION_BUDDY_APPLY_PLAYER = 159
EVENT_ACTION_BUDDY_ADD_PLAYER = 160
EVENT_ACTION_BUDDY_REMOVE_PLAYER = 161
EVENT_ACTION_BUDDY_REFUSE_PLAYER = 162
EVENT_ACTION_BUDDY_SEND_STAMINA = 163
EVENT_ACTION_BUDDY_RECEIVE_STAMINA = 164
EVENT_ACTION_BUDDY_RECEIVE_STAMINA_ALL = 165
EVENT_ACTION_BUDDY_SEND_MAIL = 166
EVENT_ACTION_UNION_CHAT = 167
EVENT_ACTION_ACTIVITY_HOLIDAY_SHOP = 168   # 活动_假日商店
EVENT_ACTION_ACTIVITY_TIME_LIMITED_SHOP = 169   # 活动_便利商店
EVENT_ACTION_ACTIVITY_TIME_LIMITED_SHIFT_SHOP = 170   # 活动_友好商店
EVENT_ACTION_FRAGMENT_SHOP_BUY = 171

EVENT_ACTION_UNION_SHOP_BUY = 172
EVENT_ACTION_UNION_APPLY_JOIN = 173
EVENT_ACTION_UNION_ACCEPT_ADD_MEMBER = 174
EVENT_ACTION_UNION_CREATE = 175
EVENT_ACTION_UNION_DISMISS = 176
EVENT_ACTION_UNION_KICK_MEMBER = 177
EVENT_ACTION_UNION_EXIT = 178
EVENT_ACTION_UNION_SET_LEADER = 179
EVENT_ACTION_UNION_BUY_REWARD = 180
EVENT_ACTION_UNION_SIGN = 181
EVENT_ACTION_UNION_STAGE_BUY_COUNT = 182
EVENT_ACTION_UNION_ATTACK_STAGE = 183
EVENT_ACTION_UNION_PASS_STAGE_REWARD_POINT = 184
EVENT_ACTION_UNION_PASS_STAGE_CHEST = 185
EVENT_ACTION_UNION_SIGN_REWARD = 186

EVENT_ACTION_TRIAL_ESSENSE_WIN = 187
EVENT_ACTION_TRIAL_ESSENSE_FAIL = 188  # 试炼战斗失败
EVENT_ACTION_CHEST_OPEN = 189
EVENT_ACTION_MAX = 190  # 游戏事件最大值 每次插入事件后修改 数值为最后一个事件ID+1


EVENT_LOG_ACTION_DICT = {
    EVENT_ACTION_CREATE_ROLE: '0-创建角色',
    EVENT_ACTION_ROLE_LOGIN: '1-角色登录',
    EVENT_ACTION_LOGOUT: '2-角色退出',
    EVENT_ACTION_DISCONNECTED: '3-角色断线',
    EVENT_ACTION_MUTE: '4-角色被踢',
    EVENT_ACTION_GET_QUEST: '5-接受任务',
    EVENT_ACTION_FINISH_QUEST: '6-结束任务',
    EVENT_ACTION_ARENA_WIN: '7-竞技场胜利',
    EVENT_ACTION_ARENA_FAIL: '8-竞技场失败',
    EVENT_ACTION_STONE_SHOP_BUY: '9-购买钻石商城物品',
    EVENT_ACTION_DITTO_SHOP_BUY: '10-购买百变怪商城物品',
    EVENT_ACTION_PVP_SHOP_BUY: '11-购买PVP商城物品',
    EVENT_ACTION_WORLD_BOSS_SHOP_BUY: '12-购买世界BOSS商城物品',
    EVENT_ACTION_ROLE_LEVEL_UP: '13-角色升级',
    EVENT_ACTION_STAGE_NORMAL_WIN: '14-普通副本战斗胜利',
    EVENT_ACTION_STAGE_HERO_WIN: '15-困难副本战斗胜利',
    EVENT_ACTION_STAGE_EXP_WIN: '16-经验副本战斗胜利',
    EVENT_ACTION_STAGE_GOLD_WIN: '17-金币副本战斗胜利',
    EVENT_ACTION_STAGE_NORMAL_FAIL: '18-普通副本战斗失败',
    EVENT_ACTION_STAGE_HERO_FAIL: '19-困难副本战斗失败',
    EVENT_ACTION_STAGE_EXP_FAIL: '20-经验副本战斗失败',
    EVENT_ACTION_STAGE_GOLD_FAIL: '21-金币副本战斗失败',
    EVENT_ACTION_FISHING_ONCE: '22-钓鱼一次',
    EVENT_ACTION_FISHING_LOOP: '23-一键钓鱼',
    EVENT_ACTION_I_INVITE_REWARD: '24-邀请好友奖励',
    EVENT_ACTION_INVITE_ME_REWARD: '25-被邀请奖励',
    EVENT_ACTION_EQUIP_SELL: '26-装备售出',
    EVENT_ACTION_GYM_FAIL: '27-挑战道馆失败',
    EVENT_ACTION_GYM_RESET: '28-道馆重置',
    EVENT_ACTION_MONSTER_FREE: '29-宠物放生',
    EVENT_ACTION_FINGER_GUESS_EXCHANGE: '31-猜拳',
    EVENT_ACTION_SUN_STONE_EXCHANGE: '32-进化石兑换',
    EVENT_ACTION_EXCHANGE_MONSTER: '33-金色精华兑换百变怪',
    EVENT_ACTION_GET_SYSTEM_MAIL_REWARD: '34-邮件奖励',
    EVENT_ACTION_GET_MONSTER_LEVEL: '35-宠物等级奖励',
    EVENT_ACTION_GET_MONSTER_STAR_LEVEL: '36-宠物星级奖励',
    EVENT_ACTION_GET_MONSTER_KIND: '37-宠物种类奖励',
    EVENT_ACTION_GET_MONSTER_QUALITY: '38-宠物品质奖励',
    EVENT_ACTION_GET_CATCH_MONSTER_RESULT: '39-抓宠关卡奖励',
    EVENT_ACTION_ONE_DRAW: '40-单抽',
    EVENT_ACTION_TEN_DRAW: '41-十连抽',
    EVENT_ACTION_EXCHANGE_ITEM: '42-装备兑换',
    EVENT_ACTION_EXCHANGE_GIFT: '43-兑换码奖励',
    EVENT_ACTION_GET_FIRST_RECHARGE_GIFT: '45-首次充值礼包',
    EVENT_ACTION_DROP_ITEM_PACKET_IN_WB: '46-世界boss领奖表掉落物品包',
    EVENT_ACTION_LOGIN_7_REWARD: '47-玩家7天登陆领奖',
    EVENT_ACTION_MASSAGE_REWARD: '48-皮卡丘按摩领取奖励',
    EVENT_ACTION_FREE_MONSTER_GET_ITEMS: '49-宠物转换为金色精华',
    EVENT_ACTION_DAILY_RECHARGE_REWARD: '51-充值每日登陆奖励',
    EVENT_ACTION_FINISH_GUIDE: '52-玩家完成某项引导',
    EVENT_ACTION_SUM_RECHARGE_REWARD: '53-累计充值奖励',
    EVENT_ACTION_SIGN_30: '56-30天签到',
    EVENT_ACTION_TRIAL_BATTLE_WIN: '58-试炼战斗',
    EVENT_ACTION_VIP_DAILY_REWARD: '59-VIP每日福利',
    EVENT_ACTION_VIP_LEVEL_GIFT: '60-VIP等级礼包',
    EVENT_ACTION_SELL_ITEM: '61-卖掉物品',
    EVENT_ACTION_DAILY_REWARD_GOLD: '62-每日签到领取金币',
    EVENT_ACTION_STAGE_NORMAL_REWARD: '63-普通副本通关奖励',
    EVENT_ACTION_STAGE_ELITE_REWARD: '64-精英副本通关奖励',
    EVENT_ACTION_STAGE_HERO_REWARD: '65-英雄副本通关奖励',
    EVENT_ACTION_TEAM_POWER_REWARD: '66-队伍战斗力奖励',
    EVENT_ACTION_STAGE_NORMAL_CROWN: '67-普通副本金皇冠奖励',
    EVENT_ACTION_STAGE_ELITE_CROWN: '68-精英副本金皇冠奖励',
    EVENT_ACTION_STAGE_HERO_CROWN: '69-英雄副本金皇冠奖励',
    EVENT_ACTION_DAILY_TASK_SCORE_REWARD: '70-每日任务宝箱奖励',
    EVENT_ACTION_GYM_WIN: '71-挑战道馆胜利',
    EVENT_ACTION_ARENA_DAILY_REWARD: '72-竞技场日常奖励',
    EVENT_ACTION_QUIZ_ANSWER_TRUE: '73-问答活动回答正确',
    EVENT_ACTION_WORLD_BOSS_REWARD: '74-世界BOSS奖励',
    EVENT_ACTION_TREASURE_COMPOSE: '75-夺宝合成物品',
    EVENT_ACTION_LEVEL_GIFT: '76-等级礼包',
    EVENT_ACTION_MONTH_CARD: '77-月卡奖励',
    EVENT_ACTION_CHANGE_NAME: '78-修改名字奖励',
    EVENT_ACTION_EQUIP_LEVEL_UP: '79-装备强化一次',
    EVENT_ACTION_WB_GOLD_INSPIRE: '80-世界BOSS金币鼓舞',
    EVENT_ACTION_CHAT: '81-聊天',
    EVENT_ACTION_STONE_RESET_STONE_SHOP: '82-钻石商城刷新商品',
    EVENT_ACTION_RESET_INDIVIDUAL_COUNT: '83-重置金币洗练次数',
    EVENT_ACTION_ARENA_BUY_COUNT: '84-竞技场购买挑战次数',
    EVENT_ACTION_WB_STONE_INSPIRE: '85-世界BOSS钻石鼓舞',
    EVENT_ACTION_WB_RESET_COUNT: '86-世界BOSS重置次数',
    EVENT_ACTION_BUY_STAGE_COUNT: '87-购买关卡次数',
    EVENT_ACTION_ADVANCE_MONSTER: '88-宠物突破',
    EVENT_ACTION_EVOLUTE_MONSTER: '89-宠物进化',
    EVENT_ACTION_LEVEL_UP_MONSTER: '90-宠物升级',
    EVENT_ACTION_UPGRADE_MONSTER_SKILL: '91-宠物技能强化',
    EVENT_ACTION_GYM_SHOP_BUY: '92-道馆购买商城物品',
    EVENT_ACTION_STAGE_MOP: '93-关卡扫荡',
    EVENT_ACTION_COMPOUND_EQUIP: '94-装备碎片合成',
    EVENT_ACTION_COMPOUND_MONSTER: '95-宠物合成',
    EVENT_ACTION_GYM_REWARD: '96-道馆奖励',
    EVENT_ACTION_LOGIN_SERIES_REWARD: '98-每日累计签到奖励',
    EVENT_ACTION_SHOP_EXCHANGE: '99-限时兑换',
    EVENT_ACTION_SIGN_30_SERIES: '100-连续30天签到',
    EVENT_ACTION_LOTTERY_REWARD: '101-夺宝抽卡',
    EVENT_ACTION_ADVANCE_TITLE: '102-提升头衔',
    EVENT_ACTION_BUY_GOLD: '103-购买金币',
    EVENT_ACTION_UPDATE_STAR_MONSTER: '104-宠物升星',
    EVENT_ACTION_RESET_INDIVIDUAL_MONSTER: '105-宠物金币洗练个体值',
    EVENT_ACTION_BUY_MIAO_BANK: '106-喵银行购买',
    EVENT_ACTION_BUY_STORAGENUM: '107-购买背包格子数量',
    EVENT_ACTION_BUY_STAMINA: '108-购买体力',
    EVENT_ACTION_MODIFY_NAME: '109-修改名字',
    EVENT_ACTION_STONE_RESET_INDIVIDUAL_MONSTER: '110-怪钻石洗练',
    EVENT_ACTION_GET_MIAOBANK_REWARD: '111-获取喵银行奖励',
    EVENT_ACTION_STONE_RESET_DITTO_SHOP: '112-百变怪商城刷新商品',
    EVENT_ACTION_STONE_RESET_GYM_SHOP: '113-道馆商城刷新商品',
    EVENT_ACTION_STONE_RESET_PVP_SHOP: '114-PVP商城刷新商品',
    EVENT_ACTION_STONE_RESET_WB_SHOP: '115-世界BOSS商城刷新商品',
    EVENT_ACTION_GYM_MOP: '118-道馆扫荡',
    EVENT_ACTION_MONSTER_REBIRTH: '119-重生',
    EVENT_ACTION_EQUIP_EXCHANGE_GET_ITEMS: '120-装备转换返还',
    EVENT_ACTION_FINISH_NEWBIE: '121-完成某项新手引导',
    EVENT_ACTION_DAILY_REWARD_STONE: '122-每日签到领取钻石',
    EVENT_ACTION_DAILY_TASK_TASK_REWARD: '123-每日任务领取奖励',
    EVENT_ACTION_TREASURE_LEVEL_UP: '124-宝石强化升级',
    EVENT_ACTION_TREASURE_PHASE_UP: '125-宝石升阶',
    EVENT_ACTION_ACTIVITY_SEVEN_LEVEL_REWARD: '126-开服七天等级奖励',
    EVENT_ACTION_ACTIVITY_SEVEN_POWER_REWARD: '127-开服七天战力奖励',
    EVENT_ACTION_EQUIP_LEVEL_UP_MULTI: '128-强化装备多次',
    EVENT_ACTION_ACTIVITY_NORMAL_STAGE_REWARD: '129-普通副本完成次数奖励',
    EVENT_ACTION_ACTIVITY_HARD_STAGE_REWARD: '130-困难副本完成次数奖励',
    EVENT_ACTION_ACTIVITY_ARENA_REWARD: '131-竞技场完成次数奖励',
    EVENT_ACTION_ACTIVITY_GYM_REWARD: '132-道馆完成次数奖励',
    EVENT_ACTION_ACTIVITY_TREASURE_REWARD: '133-夺宝完成次数奖励',
    EVENT_ACTION_ACTIVITY_FISHING_REWARD: '134-钓鱼完成次数奖励',
    EVENT_ACTION_ACTIVITY_FINGER_GUESS_REWARD: '135-猜拳完成次数奖励',
    EVENT_ACTION_ACTIVITY_RECHARGE_SHORT: '136-短期充值奖励',
    EVENT_ACTION_ACTIVITY_RECHARGE_LONG: '137-长期充值奖励',
    EVENT_ACTION_ZONE_GOLD_CROWN_REWARD: '138-获取关卡金皇冠奖励',
    EVENT_ACTION_ZONE_PASS_REWARD: '139-获取关卡通过奖励',
    EVENT_ACTION_GET_TONIC: '140-进补',
    EVENT_ACTION_TREASURE_BATTLE_WIN: '141-夺宝战斗胜利',
    EVENT_ACTION_TREASURE_BATTLE_FAIL: '142-夺宝战斗失败',
    EVENT_ACTION_WORLD_BOSS_ATTACK: '143-世界BOSS攻击',
    EVENT_ACTION_TRIAL_BATTLE_FAIL: '144-试炼战斗失败',
    EVENT_ACTION_TREASURE_COUNT_RESET: '145-夺宝次数重置',
    EVENT_ACTION_EXP_STAGE_BUY_COUNT: '146-经验副本购买挑战次数',
    EVENT_ACTION_GOLD_STAGE_BUY_COUNT: '147-金币副本购买挑战次数',
    EVENT_ACTION_RECHARGE_PLAYER: '148-外部玩家充值',
    EVENT_ACTION_RECHARGE_INNER: '149-内部充值',
    EVENT_ACTION_COMBAT_POWER_ERROR: '150-战斗力数据异常',
    EVENT_ACTION_ACTIVITY_ONE_RECHARGE: '151-单笔充值活动',
    EVENT_ACTION_ACTIVITY_WEIXIN_SHARE: '152-微信分享活动',
    EVENT_ACTION_ACTIVITY_REGIST_RECHARGE: '153-豪华签到',
    EVENT_ACTION_BUDDY_CONTACT: '154-好友通讯',
    EVENT_ACTION_REWARD_BUDDY_CONTACT: '155-领取通讯进度奖励',
    EVENT_ACTION_STONE_RESET_UNION_SHOP: '156-联盟商店重置',
    EVENT_ACTION_ACTIVITY_STONE_CONSUMPTION_REWARD: '157-活动_钻石消耗奖励',
    EVENT_ACTION_HISTORY_BUDDY_MAX_REWARD: '158-宝藏_历史好友最高数',

    EVENT_ACTION_BUDDY_APPLY_PLAYER: '159-申请好友',
    EVENT_ACTION_BUDDY_ADD_PLAYER: '160-添加好友',
    EVENT_ACTION_BUDDY_REMOVE_PLAYER: '161-删除好友',
    EVENT_ACTION_BUDDY_REFUSE_PLAYER:  '162-拒绝好友',
    EVENT_ACTION_BUDDY_SEND_STAMINA: '163-给好友发体力',
    EVENT_ACTION_BUDDY_RECEIVE_STAMINA: '164-领取好友赠送体力',
    EVENT_ACTION_BUDDY_RECEIVE_STAMINA_ALL: '165-一键领取好友赠送体力',
    EVENT_ACTION_BUDDY_SEND_MAIL: '166-给好友发私信',
    EVENT_ACTION_UNION_CHAT: '167-联盟聊天',
    EVENT_ACTION_ACTIVITY_HOLIDAY_SHOP: '168-活动_假日商店',
    EVENT_ACTION_ACTIVITY_TIME_LIMITED_SHOP: '169-活动_便利商店',
    EVENT_ACTION_ACTIVITY_TIME_LIMITED_SHIFT_SHOP: '170-活动_友好商店',
    EVENT_ACTION_FRAGMENT_SHOP_BUY: '171-碎片商城购买',
    EVENT_ACTION_UNION_SHOP_BUY: '172-联盟商城购买',
    EVENT_ACTION_UNION_APPLY_JOIN: '173-申请加入联盟',
    EVENT_ACTION_UNION_ACCEPT_ADD_MEMBER: '174-添加联盟成员',
    EVENT_ACTION_UNION_CREATE: '175-创建联盟',
    EVENT_ACTION_UNION_DISMISS: '176-解散联盟',
    EVENT_ACTION_UNION_KICK_MEMBER: '177-移除联盟成员',
    EVENT_ACTION_UNION_EXIT: '178-联盟成员退出',
    EVENT_ACTION_UNION_SET_LEADER: '179-转让联盟领导',
    EVENT_ACTION_UNION_BUY_REWARD: '180-领取联盟奖励',
    EVENT_ACTION_UNION_SIGN: '181-联盟签到',
    EVENT_ACTION_UNION_STAGE_BUY_COUNT: '182-购买联盟战斗次数',
    EVENT_ACTION_UNION_ATTACK_STAGE: '183-攻打联盟关卡',
    EVENT_ACTION_UNION_PASS_STAGE_REWARD_POINT: '184-联盟通关点数奖励',
    EVENT_ACTION_UNION_PASS_STAGE_CHEST: '185-联盟通关宝箱奖励',
    EVENT_ACTION_UNION_SIGN_REWARD: '186-联盟签到奖励',
    EVENT_ACTION_TRIAL_ESSENSE_WIN: '187-熔炼精华胜利',
    EVENT_ACTION_TRIAL_ESSENSE_FAIL: '188-熔炼精华失败',
    EVENT_ACTION_CHEST_OPEN: '189-开启宝箱',

}


EVENT_LOG_ACTION_SQL_NAME_DICT = {
    EVENT_ACTION_CREATE_ROLE: 'EVENT_ACTION_CREATE_ROLE',
    EVENT_ACTION_ROLE_LOGIN: 'EVENT_ACTION_ROLE_LOGIN',
    EVENT_ACTION_LOGOUT: 'EVENT_ACTION_LOGOUT',
    EVENT_ACTION_DISCONNECTED: 'EVENT_ACTION_DISCONNECTED',
    EVENT_ACTION_MUTE: 'EVENT_ACTION_MUTE',
    EVENT_ACTION_GET_QUEST: 'EVENT_ACTION_GET_QUEST',
    EVENT_ACTION_FINISH_QUEST: 'EVENT_ACTION_FINISH_QUEST',
    EVENT_ACTION_ARENA_WIN: 'EVENT_ACTION_ARENA_WIN',
    EVENT_ACTION_ARENA_FAIL: 'EVENT_ACTION_ARENA_FAIL',
    EVENT_ACTION_STONE_SHOP_BUY: 'EVENT_ACTION_STONE_SHOP_BUY',
    EVENT_ACTION_DITTO_SHOP_BUY: 'EVENT_ACTION_DITTO_SHOP_BUY',
    EVENT_ACTION_PVP_SHOP_BUY: 'EVENT_ACTION_PVP_SHOP_BUY',
    EVENT_ACTION_WORLD_BOSS_SHOP_BUY: 'EVENT_ACTION_WORLD_BOSS_SHOP_BUY',
    EVENT_ACTION_ROLE_LEVEL_UP: 'EVENT_ACTION_ROLE_LEVEL_UP',
    EVENT_ACTION_STAGE_NORMAL_WIN: 'EVENT_ACTION_STAGE_NORMAL_WIN',
    EVENT_ACTION_STAGE_HERO_WIN: 'EVENT_ACTION_STAGE_HERO_WIN',
    EVENT_ACTION_STAGE_EXP_WIN: 'EVENT_ACTION_STAGE_EXP_WIN',
    EVENT_ACTION_STAGE_GOLD_WIN: 'EVENT_ACTION_STAGE_GOLD_WIN',
    EVENT_ACTION_STAGE_NORMAL_FAIL: 'EVENT_ACTION_STAGE_NORMAL_FAIL',
    EVENT_ACTION_STAGE_HERO_FAIL: 'EVENT_ACTION_STAGE_HERO_FAIL',
    EVENT_ACTION_STAGE_EXP_FAIL: 'EVENT_ACTION_STAGE_EXP_FAIL',
    EVENT_ACTION_STAGE_GOLD_FAIL: 'EVENT_ACTION_STAGE_GOLD_FAIL',
    EVENT_ACTION_FISHING_ONCE: 'EVENT_ACTION_FISHING_ONCE',
    EVENT_ACTION_FISHING_LOOP: 'EVENT_ACTION_FISHING_LOOP',
    EVENT_ACTION_I_INVITE_REWARD: 'EVENT_ACTION_I_INVITE_REWARD',
    EVENT_ACTION_INVITE_ME_REWARD: 'EVENT_ACTION_INVITE_ME_REWARD',
    EVENT_ACTION_EQUIP_SELL: 'EVENT_ACTION_EQUIP_SELL',
    EVENT_ACTION_GYM_FAIL: 'EVENT_ACTION_GYM_FAIL',
    EVENT_ACTION_GYM_RESET: 'EVENT_ACTION_GYM_RESET',
    EVENT_ACTION_MONSTER_FREE: 'EVENT_ACTION_MONSTER_FREE',
    EVENT_ACTION_FINGER_GUESS_EXCHANGE: 'EVENT_ACTION_FINGER_GUESS_EXCHANGE',
    EVENT_ACTION_SUN_STONE_EXCHANGE: 'EVENT_ACTION_SUN_STONE_EXCHANGE',
    EVENT_ACTION_EXCHANGE_MONSTER: 'EVENT_ACTION_EXCHANGE_MONSTER',
    EVENT_ACTION_GET_SYSTEM_MAIL_REWARD: 'EVENT_ACTION_GET_SYSTEM_MAIL_REWARD',
    EVENT_ACTION_GET_MONSTER_LEVEL: 'EVENT_ACTION_GET_MONSTER_LEVEL',
    EVENT_ACTION_GET_MONSTER_STAR_LEVEL: 'EVENT_ACTION_GET_MONSTER_STAR_LEVEL',
    EVENT_ACTION_GET_MONSTER_KIND: 'EVENT_ACTION_GET_MONSTER_KIND',
    EVENT_ACTION_GET_MONSTER_QUALITY: 'EVENT_ACTION_GET_MONSTER_QUALITY',
    EVENT_ACTION_GET_CATCH_MONSTER_RESULT: 'EVENT_ACTION_GET_CATCH_MONSTER_RESULT',
    EVENT_ACTION_ONE_DRAW: 'EVENT_ACTION_ONE_DRAW',
    EVENT_ACTION_TEN_DRAW: 'EVENT_ACTION_TEN_DRAW',
    EVENT_ACTION_EXCHANGE_ITEM: 'EVENT_ACTION_EXCHANGE_ITEM',
    EVENT_ACTION_EXCHANGE_GIFT: 'EVENT_ACTION_EXCHANGE_GIFT',
    EVENT_ACTION_GET_FIRST_RECHARGE_GIFT: 'EVENT_ACTION_GET_FIRST_RECHARGE_GIFT',
    EVENT_ACTION_DROP_ITEM_PACKET_IN_WB: 'EVENT_ACTION_DROP_ITEM_PACKET_IN_WB',
    EVENT_ACTION_LOGIN_7_REWARD: 'EVENT_ACTION_LOGIN_7_REWARD',
    EVENT_ACTION_MASSAGE_REWARD: 'EVENT_ACTION_MASSAGE_REWARD',
    EVENT_ACTION_FREE_MONSTER_GET_ITEMS: 'EVENT_ACTION_FREE_MONSTER_GET_ITEMS',
    EVENT_ACTION_DAILY_RECHARGE_REWARD: 'EVENT_ACTION_DAILY_RECHARGE_REWARD',
    EVENT_ACTION_FINISH_GUIDE: 'EVENT_ACTION_FINISH_GUIDE',
    EVENT_ACTION_SUM_RECHARGE_REWARD: 'EVENT_ACTION_SUM_RECHARGE_REWARD',
    EVENT_ACTION_SIGN_30: 'EVENT_ACTION_SIGN_30',
    EVENT_ACTION_TRIAL_BATTLE_WIN: 'EVENT_ACTION_TRIAL_BATTLE_WIN',
    EVENT_ACTION_VIP_DAILY_REWARD: 'EVENT_ACTION_VIP_DAILY_REWARD',
    EVENT_ACTION_VIP_LEVEL_GIFT: 'EVENT_ACTION_VIP_LEVEL_GIFT',
    EVENT_ACTION_SELL_ITEM: 'EVENT_ACTION_SELL_ITEM',
    EVENT_ACTION_DAILY_REWARD_GOLD: 'EVENT_ACTION_DAILY_REWARD_GOLD',
    EVENT_ACTION_STAGE_NORMAL_REWARD: 'EVENT_ACTION_STAGE_NORMAL_REWARD',
    EVENT_ACTION_STAGE_ELITE_REWARD: 'EVENT_ACTION_STAGE_ELITE_REWARD',
    EVENT_ACTION_STAGE_HERO_REWARD: 'EVENT_ACTION_STAGE_HERO_REWARD',
    EVENT_ACTION_TEAM_POWER_REWARD: 'EVENT_ACTION_TEAM_POWER_REWARD',
    EVENT_ACTION_STAGE_NORMAL_CROWN: 'EVENT_ACTION_STAGE_NORMAL_CROWN',
    EVENT_ACTION_STAGE_ELITE_CROWN: 'EVENT_ACTION_STAGE_ELITE_CROWN',
    EVENT_ACTION_STAGE_HERO_CROWN: 'EVENT_ACTION_STAGE_HERO_CROWN',
    EVENT_ACTION_DAILY_TASK_SCORE_REWARD: 'EVENT_ACTION_DAILY_TASK_SCORE_REWARD',
    EVENT_ACTION_GYM_WIN: 'EVENT_ACTION_GYM_WIN',
    EVENT_ACTION_ARENA_DAILY_REWARD: 'EVENT_ACTION_ARENA_DAILY_REWARD',
    EVENT_ACTION_QUIZ_ANSWER_TRUE: 'EVENT_ACTION_QUIZ_ANSWER_TRUE',
    EVENT_ACTION_WORLD_BOSS_REWARD: 'EVENT_ACTION_WORLD_BOSS_REWARD',
    EVENT_ACTION_TREASURE_COMPOSE: 'EVENT_ACTION_TREASURE_COMPOSE',
    EVENT_ACTION_LEVEL_GIFT: 'EVENT_ACTION_LEVEL_GIFT',
    EVENT_ACTION_MONTH_CARD: 'EVENT_ACTION_MONTH_CARD',
    EVENT_ACTION_CHANGE_NAME: 'EVENT_ACTION_CHANGE_NAME',
    EVENT_ACTION_EQUIP_LEVEL_UP: 'EVENT_ACTION_EQUIP_LEVEL_UP',
    EVENT_ACTION_WB_GOLD_INSPIRE: 'EVENT_ACTION_WB_GOLD_INSPIRE',
    EVENT_ACTION_CHAT: 'EVENT_ACTION_CHAT',
    EVENT_ACTION_STONE_RESET_STONE_SHOP: 'EVENT_ACTION_STONE_RESET_STONE_SHOP',
    EVENT_ACTION_RESET_INDIVIDUAL_COUNT: 'EVENT_ACTION_RESET_INDIVIDUAL_COUNT',
    EVENT_ACTION_ARENA_BUY_COUNT: 'EVENT_ACTION_ARENA_BUY_COUNT',
    EVENT_ACTION_WB_STONE_INSPIRE: 'EVENT_ACTION_WB_STONE_INSPIRE',
    EVENT_ACTION_WB_RESET_COUNT: 'EVENT_ACTION_WB_RESET_COUNT',
    EVENT_ACTION_BUY_STAGE_COUNT: 'EVENT_ACTION_BUY_STAGE_COUNT',
    EVENT_ACTION_ADVANCE_MONSTER: 'EVENT_ACTION_ADVANCE_MONSTER',
    EVENT_ACTION_EVOLUTE_MONSTER: 'EVENT_ACTION_EVOLUTE_MONSTER',
    EVENT_ACTION_LEVEL_UP_MONSTER: 'EVENT_ACTION_LEVEL_UP_MONSTER',
    EVENT_ACTION_UPGRADE_MONSTER_SKILL: 'EVENT_ACTION_UPGRADE_MONSTER_SKILL',
    EVENT_ACTION_GYM_SHOP_BUY: 'EVENT_ACTION_GYM_SHOP_BUY',
    EVENT_ACTION_STAGE_MOP: 'EVENT_ACTION_STAGE_MOP',
    EVENT_ACTION_COMPOUND_EQUIP: 'EVENT_ACTION_COMPOUND_EQUIP',
    EVENT_ACTION_COMPOUND_MONSTER: 'EVENT_ACTION_COMPOUND_MONSTER',
    EVENT_ACTION_GYM_REWARD: 'EVENT_ACTION_GYM_REWARD',
    EVENT_ACTION_LOGIN_SERIES_REWARD: 'EVENT_ACTION_LOGIN_SERIES_REWARD',
    EVENT_ACTION_SHOP_EXCHANGE: 'EVENT_ACTION_SHOP_EXCHANGE',
    EVENT_ACTION_SIGN_30_SERIES: 'EVENT_ACTION_SIGN_30_SERIES',
    EVENT_ACTION_LOTTERY_REWARD: 'EVENT_ACTION_LOTTERY_REWARD',
    EVENT_ACTION_ADVANCE_TITLE: 'EVENT_ACTION_ADVANCE_TITLE',
    EVENT_ACTION_BUY_GOLD: 'EVENT_ACTION_BUY_GOLD',
    EVENT_ACTION_UPDATE_STAR_MONSTER: 'EVENT_ACTION_UPDATE_STAR_MONSTER',
    EVENT_ACTION_RESET_INDIVIDUAL_MONSTER: 'EVENT_ACTION_RESET_INDIVIDUAL_MONSTER',
    EVENT_ACTION_BUY_MIAO_BANK: 'EVENT_ACTION_BUY_MIAO_BANK',
    EVENT_ACTION_BUY_STORAGENUM: 'EVENT_ACTION_BUY_STORAGENUM',
    EVENT_ACTION_BUY_STAMINA: 'EVENT_ACTION_BUY_STAMINA',
    EVENT_ACTION_MODIFY_NAME: 'EVENT_ACTION_MODIFY_NAME',
    EVENT_ACTION_STONE_RESET_INDIVIDUAL_MONSTER: 'EVENT_ACTION_STONE_RESET_INDIVIDUAL_MONSTER',
    EVENT_ACTION_GET_MIAOBANK_REWARD: 'EVENT_ACTION_GET_MIAOBANK_REWARD',
    EVENT_ACTION_STONE_RESET_DITTO_SHOP: 'EVENT_ACTION_STONE_RESET_DITTO_SHOP',
    EVENT_ACTION_STONE_RESET_GYM_SHOP: 'EVENT_ACTION_STONE_RESET_GYM_SHOP',
    EVENT_ACTION_STONE_RESET_PVP_SHOP: 'EVENT_ACTION_STONE_RESET_PVP_SHOP',
    EVENT_ACTION_STONE_RESET_WB_SHOP: 'EVENT_ACTION_STONE_RESET_WB_SHOP',
    EVENT_ACTION_GYM_MOP: 'EVENT_ACTION_GYM_MOP',
    EVENT_ACTION_MONSTER_REBIRTH: 'EVENT_ACTION_MONSTER_REBIRTH',
    EVENT_ACTION_EQUIP_EXCHANGE_GET_ITEMS: 'EVENT_ACTION_EQUIP_EXCHANGE_GET_ITEMS',
    EVENT_ACTION_FINISH_NEWBIE: 'EVENT_ACTION_FINISH_NEWBIE',
    EVENT_ACTION_DAILY_REWARD_STONE: 'EVENT_ACTION_DAILY_REWARD_STONE',
    EVENT_ACTION_DAILY_TASK_TASK_REWARD: 'EVENT_ACTION_DAILY_TASK_TASK_REWARD',
    EVENT_ACTION_TREASURE_LEVEL_UP: 'EVENT_ACTION_TREASURE_LEVEL_UP',
    EVENT_ACTION_TREASURE_PHASE_UP: 'EVENT_ACTION_TREASURE_PHASE_UP',
    EVENT_ACTION_ACTIVITY_SEVEN_LEVEL_REWARD: 'EVENT_ACTION_ACTIVITY_SEVEN_LEVEL_REWARD',
    EVENT_ACTION_ACTIVITY_SEVEN_POWER_REWARD: 'EVENT_ACTION_ACTIVITY_SEVEN_POWER_REWARD',
    EVENT_ACTION_EQUIP_LEVEL_UP_MULTI: 'EVENT_ACTION_EQUIP_LEVEL_UP_MULTI',
    EVENT_ACTION_ACTIVITY_NORMAL_STAGE_REWARD: 'EVENT_ACTION_ACTIVITY_NORMAL_STAGE_REWARD',
    EVENT_ACTION_ACTIVITY_HARD_STAGE_REWARD: 'EVENT_ACTION_ACTIVITY_HARD_STAGE_REWARD',
    EVENT_ACTION_ACTIVITY_ARENA_REWARD: 'EVENT_ACTION_ACTIVITY_ARENA_REWARD',
    EVENT_ACTION_ACTIVITY_GYM_REWARD: 'EVENT_ACTION_ACTIVITY_GYM_REWARD',
    EVENT_ACTION_ACTIVITY_TREASURE_REWARD: 'EVENT_ACTION_ACTIVITY_TREASURE_REWARD',
    EVENT_ACTION_ACTIVITY_FISHING_REWARD: 'EVENT_ACTION_ACTIVITY_FISHING_REWARD',
    EVENT_ACTION_ACTIVITY_FINGER_GUESS_REWARD: 'EVENT_ACTION_ACTIVITY_FINGER_GUESS_REWARD',
    EVENT_ACTION_ACTIVITY_RECHARGE_SHORT: 'EVENT_ACTION_ACTIVITY_RECHARGE_SHORT',
    EVENT_ACTION_ACTIVITY_RECHARGE_LONG: 'EVENT_ACTION_ACTIVITY_RECHARGE_LONG',
    EVENT_ACTION_ZONE_GOLD_CROWN_REWARD: 'EVENT_ACTION_ZONE_GOLD_CROWN_REWARD',
    EVENT_ACTION_ZONE_PASS_REWARD: 'EVENT_ACTION_ZONE_PASS_REWARD',
    EVENT_ACTION_GET_TONIC: 'EVENT_ACTION_GET_TONIC',
    EVENT_ACTION_TREASURE_BATTLE_WIN: 'EVENT_ACTION_TREASURE_BATTLE_WIN',
    EVENT_ACTION_TREASURE_BATTLE_FAIL: 'EVENT_ACTION_TREASURE_BATTLE_FAIL',
    EVENT_ACTION_WORLD_BOSS_ATTACK: 'EVENT_ACTION_WORLD_BOSS_ATTACK',
    EVENT_ACTION_TRIAL_BATTLE_FAIL: 'EVENT_ACTION_TRIAL_BATTLE_FAIL',
    EVENT_ACTION_TREASURE_COUNT_RESET: 'EVENT_ACTION_TREASURE_COUNT_RESET',
    EVENT_ACTION_EXP_STAGE_BUY_COUNT: 'EVENT_ACTION_EXP_STAGE_BUY_COUNT',
    EVENT_ACTION_GOLD_STAGE_BUY_COUNT: 'EVENT_ACTION_GOLD_STAGE_BUY_COUNT',
    EVENT_ACTION_RECHARGE_PLAYER: 'EVENT_ACTION_RECHARGE_PLAYER',
    EVENT_ACTION_RECHARGE_INNER: 'EVENT_ACTION_RECHARGE_INNER',
    EVENT_ACTION_COMBAT_POWER_ERROR: 'EVENT_ACTION_COMBAT_POWER_ERROR',
    EVENT_ACTION_ACTIVITY_ONE_RECHARGE: 'EVENT_ACTION_ACTIVITY_ONE_RECHARGE',
    EVENT_ACTION_ACTIVITY_WEIXIN_SHARE: 'EVENT_ACTION_ACTIVITY_WEIXIN_SHARE',
    EVENT_ACTION_ACTIVITY_REGIST_RECHARGE: 'EVENT_ACTION_ACTIVITY_REGIST_RECHARGE',
    EVENT_ACTION_BUDDY_CONTACT: 'EVENT_ACTION_BUDDY_CONTACT',
    EVENT_ACTION_REWARD_BUDDY_CONTACT:  'EVENT_ACTION_REWARD_BUDDY_CONTACT',
    EVENT_ACTION_STONE_RESET_UNION_SHOP: 'EVENT_ACTION_STONE_RESET_UNION_SHOP',
    EVENT_ACTION_ACTIVITY_STONE_CONSUMPTION_REWARD: 'EVENT_ACTION_ACTIVITY_STONE_CONSUMPTION_REWARD',
    EVENT_ACTION_HISTORY_BUDDY_MAX_REWARD: 'EVENT_ACTION_HISTORY_BUDDY_MAX_REWARD',
    EVENT_ACTION_BUDDY_APPLY_PLAYER: 'EVENT_ACTION_BUDDY_APPLY_PLAYER',
    EVENT_ACTION_BUDDY_ADD_PLAYER: 'EVENT_ACTION_BUDDY_ADD_PLAYER',
    EVENT_ACTION_BUDDY_REMOVE_PLAYER: 'EVENT_ACTION_BUDDY_REMOVE_PLAYER',
    EVENT_ACTION_BUDDY_REFUSE_PLAYER:  'EVENT_ACTION_BUDDY_REFUSE_PLAYER',
    EVENT_ACTION_BUDDY_SEND_STAMINA: 'EVENT_ACTION_BUDDY_SEND_STAMINA',
    EVENT_ACTION_BUDDY_RECEIVE_STAMINA: 'EVENT_ACTION_BUDDY_RECEIVE_STAMINA',
    EVENT_ACTION_BUDDY_RECEIVE_STAMINA_ALL: 'EVENT_ACTION_BUDDY_RECEIVE_STAMINA_ALL',
    EVENT_ACTION_BUDDY_SEND_MAIL: 'EVENT_ACTION_BUDDY_SEND_MAIL',
    EVENT_ACTION_UNION_CHAT: 'EVENT_ACTION_UNION_CHAT',
    EVENT_ACTION_ACTIVITY_HOLIDAY_SHOP: 'EVENT_ACTION_ACTIVITY_HOLIDAY_SHOP',
    EVENT_ACTION_ACTIVITY_TIME_LIMITED_SHOP: 'EVENT_ACTION_ACTIVITY_TIME_LIMITED_SHOP',
    EVENT_ACTION_ACTIVITY_TIME_LIMITED_SHIFT_SHOP: 'EVENT_ACTION_ACTIVITY_TIME_LIMITED_SHIFT_SHOP',
    EVENT_ACTION_FRAGMENT_SHOP_BUY: 'EVENT_ACTION_FRAGMENT_SHOP_BUY',
    EVENT_ACTION_UNION_SHOP_BUY: 'EVENT_ACTION_UNION_SHOP_BUY',
    EVENT_ACTION_UNION_APPLY_JOIN: 'EVENT_ACTION_UNION_APPLY_JOIN',
    EVENT_ACTION_UNION_ACCEPT_ADD_MEMBER: 'EVENT_ACTION_UNION_ACCEPT_ADD_MEMBER',
    EVENT_ACTION_UNION_CREATE: 'EVENT_ACTION_UNION_CREATE',
    EVENT_ACTION_UNION_DISMISS: 'EVENT_ACTION_UNION_DISMISS',
    EVENT_ACTION_UNION_KICK_MEMBER: 'EVENT_ACTION_UNION_KICK_MEMBER',
    EVENT_ACTION_UNION_EXIT: 'EVENT_ACTION_UNION_EXIT',
    EVENT_ACTION_UNION_SET_LEADER: 'EVENT_ACTION_UNION_SET_LEADER',
    EVENT_ACTION_UNION_BUY_REWARD: 'EVENT_ACTION_UNION_BUY_REWARD',
    EVENT_ACTION_UNION_SIGN: 'EVENT_ACTION_UNION_SIGN',
    EVENT_ACTION_UNION_STAGE_BUY_COUNT: 'EVENT_ACTION_UNION_STAGE_BUY_COUNT',
    EVENT_ACTION_UNION_ATTACK_STAGE: 'EVENT_ACTION_UNION_ATTACK_STAGE',
    EVENT_ACTION_UNION_PASS_STAGE_REWARD_POINT: 'EVENT_ACTION_UNION_PASS_STAGE_REWARD_POINT',
    EVENT_ACTION_UNION_PASS_STAGE_CHEST: 'EVENT_ACTION_UNION_PASS_STAGE_CHEST',
    EVENT_ACTION_UNION_SIGN_REWARD: 'EVENT_ACTION_UNION_SIGN_REWARD',
    EVENT_ACTION_TRIAL_ESSENSE_WIN: 'EVENT_ACTION_TRIAL_ESSENSE_WIN',
    EVENT_ACTION_TRIAL_ESSENSE_FAIL: 'EVENT_ACTION_TRIAL_ESSENSE_FAIL',
    EVENT_ACTION_CHEST_OPEN: 'EVENT_ACTION_CHEST_OPEN',
}

LOG_EVENT_VALUE = {
'action'        :       u'事件',
'log_time'	    :	    u'事件时间',
'server_id'	    :	    u'服务器',
'platform_id'	:	    u'渠道',
'uid'	        :	    u'用户ID',
'level'	        :	    u'等级',
'vip_level'	    :	u'VIP等级',
'install'	    :	u'安装时间',
'add_exp'	    :	u'增加经验',
'old_exp'	    :	u'以前经验',
'cost_fishing_count': u'钓鱼次数',
'cur_exp'	    :	u'当前经验',
'add_gold'	    :	u'增加金币',
'cost_gold'	    :	u'消耗金币',
'total_cost_stone'	:	u'总消耗宝石',
'total_cost_gold':      u'总消耗金币',
'old_gold'	:	u'以前金币',
'cur_gold'	:	u'当前金币',
'add_stone'	:	u'增加钻石',
'cost_stone'	:	u'消耗钻石',
'old_stone'	:	u'以前钻石',
'cur_stone'	:	u'当前钻石',
'add_free_draw'	:	u'增加精灵球',
'cost_free_draw'	:	u'消耗精灵球',
'old_free_draw'	:	u'以前精灵球',
'cur_free_draw'	:	u'消耗精灵球',
'add_item_list'	:	u'增加物品列表',
'cost_item_list'	:	u'消耗物品列表',
'add_monster_list'	:	u'添加宠物列表',
'remove_monster_list'	:	u'移除宠物列表',
'add_equip_list'	:	u'添加装备列表',
'remove_equip_list'	:	u'移除装备列表',
'add_gym_point'	:	u'增加道馆币',
'cost_gym_point'	:	u'消耗道馆币',
'old_gym_point'	:	u'以前道馆币',
'cur_gym_point'	:	u'当前道馆币',
'player_name'	:	u'玩家名字',
'account_id'	:	u'账户ID',
'account_name'	:	u'账户名',
'dev_id'	:	u'设备ID',
'login_ip'	:	u'登录IP',
'month_card_days'	:	u'月卡剩余天数',
'login_dis_days'	:	u'距上次登陆天数',
'role_id'	:	u'头像',
'quiz_right_count'	:	u'问答正确次数',
'add_rmb'	:	u'新充值人民币',
'total_rmb'	:	u'总共充值数',
'old_vip_level'	:	u'以前VIP等级',
'add_consumption_point'	:	u'增加消费积分',
'cost_consumption_point'	:	u'消耗消费积分',
'old_consumption_point'	:	u'以前消费积分',
'cur_consumption_point'	:	u'当前消费积分',
'add_arena_emblem'	:	u'增加竞技场纹章',
'cost_arena_emblem'	:	u'消耗纹章',
'old_arena_emblem'	:	u'以前纹章',
'cur_arena_emblem'	:	u'当前纹章',
'add_world_boss_point'	:	u'增加世界BOSS战魂',
'cost_world_boss_point'	:	u'消耗战魂',
'old_world_boss_point'	:	u'以前战魂',
'cur_world_boss_point'	:	u'当前战魂',
'stage_index'	:	u'关卡序号',
'add_universal_fragment'	:	u'增加的万能碎片',
'cost_universal_fragment'	:	u'消耗的万能碎片',
'old_universal_fragment'	:	u'以前万能碎片数量',
'cur_universal_fragment'	:	u'当前万能碎片数量',
'guide_id'	:	u'引导ID',
'add_treasure_frag_list'	:	u'增加的宝物碎片',
'remove_treasure_frag_list'	:	u'移除的宝物碎片',
'add_treasure_list'	:	u'增加的宝物',
'treasure_id'	:	u'宝物ID',
'treasure_old_exp'	:	u'宝物升级前经验',
'treasure_new_exp'	:	u'宝物升级后经验',
'treasure_old_level'	:	u'宝物升级前级别',
'treasure_new_level'	:	u'宝物升级后级别',
'treasure_level_up_material'	:	u'宝物强化消耗的材料ID列表',
'treasure_old_phase'	:	u'宝物升阶前阶级',
'treasure_new_phase'	:	u'宝物升阶后阶级',
'treasure_need_material_num'	:	u'宝物升阶需要材料数量',
'treasure_phase_up_material'	:	u'宝物升阶消耗材料ID列表',
'order_id'	:	u'充值订单号',
'shop_index19:54'	:	u'充值类别序号',
'shop_event'	:	u'充值双倍开启状态',
'old_rmb'	:	u'之前充值人民币数',
'platform_type'	:	u'充值平台ID',
'cur_rmb'	:	u'当前总充值人民币',
'former_level'	:	u'玩家升级前等级',
'former_exp'	:	u'玩家升级前经验',
'later_level'	:	u'玩家升级后等级',
'later_exp'	:	u'玩家升级后经验',
'total_challenge_count'	:	u'关卡总共已挑战次数',
'team_list'	:	u'队伍信息（tid,starLevel,level）',
'cost_stamina'	:	u'消耗体力',
'monster_tid'	:	u'金币洗练宠物tid',
'name'          :   u'玩家昵称',
'newbie_id'     :   u'新手引导序号',
'union_uid': u'联盟UID',
'add_union_point': u'增加联盟币',
'cur_union_point': u'当前联盟币'
}


#用户信息键值对

USER_INFO_DIC_TO_CHINA = {
'uid'                       :       u'UID',
'openid'	                :	    u'OpenID',
'state'	                    :	    u'状态',
'add_time'	                :	    u'安装时间',
'last_login_time'	        :	    u'最后登录时间',
'last_login_distance_days'  :       u'距离上次登录间隔时间',
'platform_id'	            :	    u'玩家平台',
'last_login_cookie_time'	:	    u'最后登录的cookie时间',
'last_player_time'	        :	    u'最后游戏时间',

}



