# coding:utf-8
MEM_KEY_NAME = {
    'newbie': u'新手阶段（影响新手教程）',
    'last_tonic_time': u'上次进补时间',
    'gold': u'金币',
    'champion_index': u'冠军宠在队伍中的位置',
    'last_finger_guess_time': u'上次猜拳时间',
    'reward_cur_monster_star_level_id': u'当前宠物星级奖励序列',
    'universal_fragment': u'一般碎片数量',
    'title': u'玩家爵位',
    'consumption_point': u'消费点数',
    'role_id': u'头像ID',
    'reward_login_series_id': u'累计登陆次数',
    'reward_login_series_time': u'累计登陆上次时间',
    'reward_cur_monster_kind_id': u'当前宠物种类奖励序列',
    'has_first_recharge_lst': u'玩家首充',
    'need_create_player': u'是否需要创建角色',
    'honour_point': u'玩家荣誉点数',
    'account_id': u'账号ID',
    'get_vip_level_gift': u'玩家已经领取的vip礼包',
    'last_stamina_time': u'上次消耗体力时间',
    'is_stone_one_draw': u'首次钻石单抽状态',
    'champion_power': u'冠军宠物战斗力',
    'guide_id_lst': u'引导的id',
    'is_ten_draw': u'首次钻石十连抽状态',
    'reset_individual_count_refresh_date': u' 玩家购买洗练次数刷新日期',
    'champion_tid': u'冠军宠物id',
    'name': u'玩家昵称',
    'level': u'玩家等级',
    'cur_stage': u'当前关卡',
    'reset_buy_gold_datetime': u'金币购买刷新时间',
    'last_get_month_50_datetime': u'上次获取月卡奖励时间',
    'last_chat_time': u'上次聊天时间',
    'has_change_name_reward': u'改名奖励是否获取',
    'challenge_winning_streak': u'竞技场玩家连续胜利记录',
    'stage_hero_total_count': u'困难副本总共已挑战次数',
    'system_notice_refresh_time': u'广播刷新时间',
    'rmb': u'充值',
    'stage_exp_total_count': u'经验副本总共已挑战次数',
    'last_daily_reward_gold': u'上次签到时间',
    'last_pikachu_massage_time': u'上次按摩时间',
    'reward_cur_monster_quality_id': u'当前宠物品质奖励序列',
    'storage_buy_num': u'购买背包数量',
    'reward_cur_team_combat_power_id': u'当前队伍战斗力奖励序列',
    'team_combat_power': u'当前队伍战斗力',
    'finger_losing_streak': u'玩家猜拳连续失败次数',
    'buy_challenge_count_time': u'玩家购买竞技场挑战次数',
    'pikachu_massage_count': u'玩家连续按摩次数',
    'finger_winning_streak': u'玩家猜拳连胜次数',
    'reward_friend_num_id': u'好友数量奖励序列',
    'stone': u'玩家钻石数量',
    'challenge_daily_reward_date': u'玩家挑战每日领奖日期',
    'finger_guess_has_exchange': u'猜拳所得已经兑换的',
    'special_draw_pink_times': u'特殊抽奖次数',
    'last_daily_reward_stone': u'上次每日奖励钻石时间',
    'stage_normal_total_count': u'普通副本总共已挑战次数',
    'last_fishing_refresh_time': u'上次钓鱼刷新时间',
    'story': u'故事',
    'challenge_date': u'玩家挑战次数刷新日期',
    'stamina': u'体力',
    'total_cost_stone': u'玩家总共消耗钻石数',
    'vip_level': u'玩家VIP等级',
    'cur_hero_stage': u'当前英雄关卡',
    'change_name_count': u'修改名字次数',
    'need_create_monster': u'是否需要创建宠物',
    'reward_cur_level_has': u'当前等级奖励序列',
    'total_cost_gold': u'玩家总共消耗金币数',
    'monster_reset_individual_count': u'怪洗练次数',
    'free_draw_material': u'精灵球数量',
    'reward_login_series_refresh': u'累计登录是否刷新',
    'stage_gold_total_count': u'金币副本总共已挑战次数',
    'finger_guess_left_time': u'玩家猜拳剩余次数',
    'is_first_recharge_gift_active': u'是否已领取首充礼包',
    'dev_id': u'版本号',
    'uid' : u'玩家UID',
    'challenge_count': u'玩家竞技场挑战次数',
    'world_boss_score': u'世界BOSS积分',
    'buy_miao_bank': u'购买喵银行',
    'finger_guess_lst': u'武藏猜拳当前列表',
    'total_challenge_win_count': u'玩家竞技场挑战获胜次数',
    'data_version': u'数据版本',
    'month_50_indate': u'月卡有效期',
    'reward_cur_monster_level_id': u'当前宠物等级奖励序列',
    'cur_max_team_combat_power': u'当前最大的队伍战斗力',
    'player_notice_refresh_time': u'玩家广播刷新时间',
    'reward_cur_miao_bank_has': u'当前喵银行的已经领奖的IDs',
    'buy_gold_times': u'购买金币次数',
    'honour_point_datetime': u'荣誉点数刷新时间',
    'buy_stamina_times': u'购买体力次数',
    'pikachu_reward': u'按摩可以领取奖励',
    'buy_reset_individual_time': u'玩家第几次怪洗练',
    'reset_buy_stamina_datetime': u'体力购买刷新时间',
    'exp': u'经验值',
    'cur_fishing_left_count': u'当前钓鱼剩余次数',
    'monster_last_reset_time':u'宠物上次洗练时间'
}

#不允许修改的关键字
FORBIDE_CHANGE_VALUES=[ 'team_combat_power', 'cur_max_team_combat_power', 'system_notice_refresh_time','player_notice_refresh_time','last_tonic_time','last_finger_guess_time',
                        'account_id','data_version','dev_id','uid','last_chat_time','monster_last_reset_time','vip_level','challenge_count','total_cost_gold','total_cost_stone','name','last_pikachu_massage_time',
                        'story',
                        ]